### ISSUE TITLE
PrefFinder: getting the right preference in configurable software systems

### ISSUE THREAD

**Issue by nave91** [opensciences/opensciences.github.io#105]
paper link: http://dl.acm.org/citation.cfm?id=2643009&CFID=609852226&CFTOKEN=49731104

possible other data links: http://cse.unl.edu/~myra/research.html

search for "artifacts"

**Comment by Amoula1** [comment]
* Title:  PrefFinder: Getting the Right Preference in Configurable Software Systems
* Authors: 
- Dongpu Jin, Lincoln, djin@cse.unl.edu
- Myra B. Cohen, myra@cse.unl.edu
- Xiao Qu, xiao.qu@us.abb.com
- Brian Robinson, brian.p.robinson@us.abb.com
* Main Objective of the paper: Facilitating the identification of the user preferences that will modify a particular system behavior.
* Contribution: Proposition of PrefFinder, a natural language framework that finds (and changes) user preferences.
* Findings: PrefFinder finds the correct answer between 76-96% of the time on more than 175 queries. When compared to asking questions on a help forum or through the company’s service center, we can potentially save days or even weeks of time.
* Data Links:
 1- http://cse.unl.edu/~myra/artifacts/SEIP-2014/
 2- http://cse.unl.edu/~myra/artifacts/PrefFinder_2014/
* Data description: In the case 1) Data  is found in the referenced paper [14] "Configurations Everywhere: Implications for Testing and Debugging in Practice".  2) We built PrefFinder versions using two open source applications from different domains (Firefox and LIbreOffice)
