### ISSUE TITLE
Retrofitting concurrency for Android applications through refactoring

### ISSUE THREAD

**Issue by mambocab** [opensciences/opensciences.github.io#107]
From [FSE'14 Chunk 3](https://github.com/opensciences/opensciences.github.io/issues/85)

Yu Lin, Cosmin Radoi, Danny Dig
Pages: 341-352
doi>10.1145/2635868.2635903
Full text: PDFPDF

The authors posted links to their data [here](http://mir.cs.illinois.edu/~yulin2/asynchronizer/). This contains links to a number of tables indicating lines in which their tool found concurrency bugs.

These tables are `.htm` files and seem to be unavailable. However, [the Google cache is available for at least some of them](http://webcache.googleusercontent.com/search?q=cache:http://mir.cs.illinois.edu/~yulin2/asynchronizer/underuse.htm).

**Comment by WeiFoo** [comment]
this link is not available  right now. So I decided to close it
