### ISSUE TITLE
Checking app behavior against app descriptions

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#110]
paper link:http://dl.acm.org/ft_gateway.cfm?id=2568276&ftid=1467964&dwn=1&CFID=609851752&CFTOKEN=92241930
dataset: use the data in reference http://www.csc.ncsu.edu/faculty/jiang/pubs/OAKLAND12.pdf

**Comment by Amoula1** [comment]
Paper Title: Checking App Behavior Against App Descriptions
Authors: 
-Alessandra Gorla
-Ilaria Tavecchia∗
-Florian Gross
-Andreas Zeller
* Emails: {gorla, tavecchia, fgross, zeller}@cs.uni-saarland.de
* Objective: Knowing when a program does what it claims to do. 
* Contribution: Proposition of CHABADA prototype that clusters apps by description topics, and identifys outliers by API usage within each cluster. 
* Findings: Our CHABADA approach effectively identifies applications whose behavior would be unexpected given their description. Experiments were applied on a set of 22,500+ Android applications, our CHABADA prototype identified several anomalies; additionally, it flagged 56% of novel malware as such, without requiring any known malware patterns.
@WeiFoo  we can access data directly using this link.
* Dataset: https://www.st.cs.uni-saarland.de/appmining/chabada/
* Data Description: we have prepared a 50 MB dataset with the exact data that goes into our CHABADA prototype.

**Comment by reesjones** [comment]
Added as [chabada](http://openscience.us/repo/other/chabada.html).
