### ISSUE TITLE
How to make best use of cross-company data in software effort estimation?

### ISSUE THREAD

**Issue by mambocab** [opensciences/opensciences.github.io#114]
[from Chunk8 ICSE 2014](https://github.com/opensciences/opensciences.github.io/issues/98)

Leandro L. Minku, Xin Yao
Pages: 446-456
doi>10.1145/2568225.2568228

[paper here](http://dl.acm.org/citation.cfm?id=2568225.2568228)

This doesn't seem to have any unique datasets, but they may have analyzed datasets we haven't yet downloaded. See Section 7, "Databases", for more information.

**Comment by behjatslt** [comment]
we already have the data in database.
