### ISSUE TITLE
Combining rule-based and information retrieval techniques to assign software change requests

### ISSUE THREAD

**Issue by nave91** [opensciences/opensciences.github.io#118]
paper: http://dl.acm.org/citation.cfm?id=2642964&CFID=609852226&CFTOKEN=49731104

search for "Brazilian Federal Data Processing Service (SERPRO)"

**Comment by Amoula1** [comment]
Link to the paper: http://sci-hub.org/downloads/8124/10.0000@www.researchgate.net@266060437.pdf

**Author, email:
Yguaratã Cerqueira Cavalcanti, ycc@cin.ufpe.br
Ivan do Carmo Machado, vanmachado@dcc.ufba.br
Paulo A. da Mota S. Neto, pamsn@cin.ufpe.br
Eduardo Santana de Almeida, esa@dcc.ufba.br
Silvio Romero de Lemos Meira, srlm@cin.ufpe.br

**Main Objective:  Facilitating the task of assigning Change Request (CR) to developers as being a labor-intensive and time consuming task.

** Main Contribution: Development of a configurable approach for semi-automated assignment of CRs which enables software analysts control its behavior, as well as, it provides a mean to support contextual information necessary to perform effective assignments.

**Evaluation Results: Results of an empirical evaluation showed that the approach is up to 46,5% more accurate than approaches which rely solely on machine learning techniques.

** Dataset: 
The CR dataset was extracted from a private software development project conducted at SERPRO.
==> It is not possible to get data as being private datasets.
