### ISSUE TITLE
ISSRE '14 Chunk #2

### ISSUE THREAD

**Issue by BenProvince** [opensciences/opensciences.github.io#119]
# Category: Data Analysis

## Analysis and Diagnosis of SLA Violations in a Production SaaS Cloud 
Catello Di Martino, Daniel Chen, Geetika Goel, Rajeshwari Ganesan, Zbigniew Kalbarczyk and Ravishankar Iyer
pages: 178-188
doi>10.1109/ISSRE.2014.26

The objective of this study is to diagnose the causes of SLA violations, pinpoint critical failure modes under realistic error assumptions and identify potential means to increase the user perceived availability of the platform and assurance of SLA requirements. We base our study on 283 days of logs obtained during the production time of the platform, while it was employed to process business data received by 42 customers in 22 countries.

Comment:  The data used here is platform logs and OS and application exception logs and covers over a period of 282 days. There is no link to the data and it a file size would be huge

vivekaxl: Can't see the data and data seems to be big

## Mutations: How Close are they to Real Faults?
Rahul Gopinath, Carlos Jensen and Alex Groce
pages: 189-200
doi>10.1109/ISSRE.2014.40

In this paper, we separately investigate the characteristics of bug-fixes and other changes in a very large set of randomly selected projects using four different programming languages. Our analysis suggests that a typical fault involves about three to four tokens, and is seldom equivalent to any traditional mutation operator.

## A Survey on Unit Testing Practices and Problems 
Ermira Daka and Gordon Fraser
pages: 201-211
doi>10.1109/ISSRE.2014.11

We conducted a survey amongst 225 software developers, covering different programming languages and 29 countries, using a global online marketing research platform. The survey responses confirm that unit testing is an important factor in software development, and suggest that there is indeed potential and need for research on automation of unit testing.

Comment: The paper conducts a survey and lists all the questions in the paper along with the analysis. I couldn't find paper offering any links to any data used in the paper

# Category: Industrial Systems

## Assessing Direct Monitoring Techniques to Analyze Failures of Critical Industrial Systems
Marcello Cinque, Domenico Cotroneo, Raffaele Della Corte and Antonio Pecchia
pages: 212-222
doi>10.1109/ISSRE.2014.30

This paper proposes an experimental evaluation of different direct monitoring techniques, namely event logs, assertions, and source code instrumentation, that are widely used in the context of critical industrial systems. We inject 12,733 software faults in a real-world air traffic control (ATC) middleware system with the aim of analyzing the ability of mentioned techniques to produce information in case of failures.

## Experince Report: Verifying Data Interaction Coverage to Improve Testing of Data-intensive Systems: The Norwegian Customs and Excise Case Study
Sagar Sen, Carlo Ieva, Arnab Sarkar, Atle Sander and Astrid Grime
pages: 223-234
doi>10.1109/ISSRE.2014.22

We present a tool-supported method to model realistic scenarios and verify whether copied test databases actually cover them and consequently facilitate adequate testing. We conceptualize realistic scenarios as data interactions between fields cross-cutting a complex database schema and model them as test cases in a classification tree model.

**Comment: No data found **

## Runtime Verification of Web Services for Interconnected Medical Devices
Normann Decker, Franziska Kühn, Martin Leucker and Daniel Thoma
pages: 235-244
doi>10.1109/ISSRE.2014.16

The presented framework uses runtime monitors synthesised from high-level specifications to ensure safety constraints. The framework has been designed for the interconnection of medical devices in the operating room.

# Category: Case Studies 2

#Access Control Policy Evolution: An Empirical Study
Jeehyun Hwang, Laurie Williams, Mladen Vouk and Da Young Lee
pages: 245-254
doi>10.1109/ISSRE.2014.36 

We analyzed ACP evolution in three systems: Security Enhanced Linux (SELinux) operating system, Virtual Computing Laboratory (VCL) cloud, and a network intrusion detection (Snort) application. We propose an approach, which extracts evolution patterns based on the analysis of ACP historical change data. 

## A Safety Engineering Tool Framework Supporting Error Model Creation and Visualization
Roland Mader, Rene Obendrauf, Philipp Prinz and Gerhard Grießnig
pages: 255-266
doi>10.1109/ISSRE.2014.37 

We present the AVL Safety Extensions in the context of the tool framework, the language SSML and the TDM focusing on the AVL Safety Extensions' capabilities for error model creation and visualization supporting safety analysis techniques such as FTA (Fault Tree Analysis) and FMEA (Failure Modes and Effects Analysis). 

##  Reproducibility of environment-dependent software failures: An Experience Report
Davide Giacomo Cavezza, Roberto Pietrantuono, Javier Alonso, Stefano Russo and Kishor Trivedi
pages: 255-266
doi>10.1109/ISSRE.2014.37

The set of failures of interest is drawn from My SQL's failure reports database and an experiment is designed for each of these failures. The experiments expose the influence of disk usage and level of concurrency on My SQL failure reproducibility.

# Category: Software Testing

## An Empirical Study on the Scalability of Selective Mutation Testing
Jie Zhang, Muyao Zhu, Dan Hao and Lu Zhang
pages: 277-287
doi>10.1109/ISSRE.2014.27 

To study the scalability of selective mutation testing, we systematically explore how the program size impacts selective mutation testing through four projects (including 12 versions all together).

## Multi-objective construction of an entire adequate test suite for an EFSM
Nesa Asoudeh and Yvan Labiche
pages: 288-299
doi>10.1109/ISSRE.2014.14

In this paper we propose a method and a tool to generate test suites from extended finite state machines, accounting for multiple (potentially conflicting) objectives. We aim at maximizing coverage and feasibility of a test suite while minimizing similarity between its test cases and minimizing overall cost.

## Using Pre-Release Test Failures to Build Early Post-Release Defect Prediction Models
Kim Herzig
pages: 300-311
doi>10.1109/ISSRE.2014.21

This paper presents an exploratory study investigating whether test execution metrics, e.g. Test failure bursts, can be used as software quality indicators and used to build pre- and post-release defects prediction models.

# Category: Applications of Machine Learning

## Defect Prediction between Software Versions with Active Learning and Dimensionality Reduction
Huihua Lu, Ekrem Kocaguneli and Bojan Cukic
pages: 312-322
doi>10.1109/ISSRE.2014.35

We propose active learning as a way to automate the development of models which improve the performance of defect prediction between successive releases. Our results show that the integration of active learning with uncertainty sampling consistently outperforms the corresponding supervised learning approach.

## An orchestrated survey of available algorithms and tools for Combinatorial Testing
Sunint Khalsa and Yvan Labiche
pages: 323-334
doi>10.1109/ISSRE.2014.15

The goal of the present work is to determine available algorithms/tools for generating a combinatorial test suite. We tried to be as complete as possible by using a precise protocol for selecting papers describing those algorithms/tools. The 75 algorithms/tools we identified are then categorized on the basis of different comparison criteria, including: the test suite generation technique, the support for selection (combination)criteria, mixed covering array, the strength of coverage, and the support for constraints between parameters.

## Predicting Effectiveness of IR-Based Bug Localization Techniques
Tien-Duy B. Le, Ferdian Thung and David Lo
pages: 335-345
doi>10.1109/ISSRE.2014.39

We build an oracle that can automatically predict whether a ranked list produced by an IR-based bug localization tool is likely to be effective or not. We consider a ranked list to be effective if a buggy file appears in the top-N position of the list.

**Comment by vivekaxl** [comment]
I have finished it!
