### ISSUE TITLE
No issue left behind: reducing information overload in issue tracking

### ISSUE THREAD

**Issue by rahulpandita** [opensciences/opensciences.github.io#122]
Link to the paper: http://plg.uwaterloo.ca/~migod/846/current/papers/icse14-olgaReid.pdf

Link to actual data Page: https://wiki.mozilla.org/Bugzilla_Anthropology

Olga Baysal, Reid Holmes, Michael W. Godfrey
Pages: 666-677
doi>10.1145/2635868.2635887
Full text: PDFPDF

Modern software development tools such as issue trackers are often complex and multi-purpose tools that provide access to an immense amount of raw information. Unfortunately, developers sometimes feel frustrated when they cannot easily obtain the particular ... expand

**Comment by rahlk** [comment]
### Categorization (effort, requirements, model, defect, etc.)
    If it doesn't fit nicely into one of these categories, put "other" and propose a category name
    Pick from the categories in the navbar on the OpenScience website.

### Author list for the paper (including emails)

### General overview of the data
    Note that this is not the abstract of the paper. If you can find an overview of the dataset in the author's own words, just copy those words. If not, make your own overview. Paragraph long (if you are making it yourself)

### Link to the paper associated with the dataset
    This should be either a link to the ACM digital library (e.g. http://dl.acm.org/citation.cfm?id=2635868.2635905), IEEE digital library (e.g. http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6982619), or some other standard library

### Paper abstract

#### BibTeX reference for the paper

### Link to the datasets
    If multiple files come with it, include links to all files, not just the parent file
    Red flags should go up if, after downloading all the data, it is larger than 100 MB (compressed)

### Is this dataset part of a larger series or collection?
    If so, link to the master index of the series or collection (if possible)

**Comment by reesjones** [comment]
Added as [mozillaanthropology](http://openscience.us/repo/other/mozillaanthropology.html).

**Comment by reesjones** [comment]
Authors emailed, data uploaded.
