### ISSUE TITLE
The Strength of Random Search on Automated Program Repair

### ISSUE THREAD

**Issue by rahlk** [opensciences/opensciences.github.io#124]
Link - http://delivery.acm.org/10.1145/2570000/2568254/p254-qi.pdf?ip=152.7.224.8&id=2568254&acc=ACTIVE%20SERVICE&key=6ABC8B4C00F6EE47%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&CFID=609849406&CFTOKEN=18730546&__acm__=1418930020_2c6a2f28bdf0888b28d0fb75f25be607

Alternate Link - http://qiyuhua.github.io/publications/icse2014-qi.pdf

**Comment by reesjones** [comment]
Data is ~5GB! Closing.
