### ISSUE TITLE
 The impact of code review coverage and code review participation on software quality: a case study of the qt, VTK, and ITK projects

### ISSUE THREAD

**Issue by CorbinSteele** [opensciences/opensciences.github.io#125]
### Notes
__Categorization:__ Other
__Authors:__ [	Shane McIntosh](mailto:mcintosh@cs.queensu.ca),  [Yasutaka Kamei](mailto:kamei@ait.kyushu-u.ac.jp), [Bram Adams](mailto:bram.adams@polymtl.ca), and [Ahmed E. Hassan](mailto:ahmed@cs.queensu.ca)
__General overview of the data:__

In order to evaluate the impact that code review coverage and participation have on software quality,  the authors extract code review data from the Gerrit review databases of the studied systems, and link the review data to the integrated patches recorded in the corresponding VCSs.

The data extraction approach is broken down into three steps:  (1) extract review data from the Gerrit review database, (2) extract Gerrit change IDs from the VCS commits, and (3) calculate version control metrics.

__Link:__ [The impact of code review coverage and code review participation on software quality: a case study of the qt, VTK, and ITK projects](http://dl.acm.org/citation.cfm?id=2597076)
__Bibtex:__ 
```tex
@inproceedings{McIntosh:2014:ICR:2597073.2597076,
 author = {McIntosh, Shane and Kamei, Yasutaka and Adams, Bram and Hassan, Ahmed E.},
 title = {The Impact of Code Review Coverage and Code Review Participation on Software Quality: A Case Study of the Qt, VTK, and ITK Projects},
 booktitle = {Proceedings of the 11th Working Conference on Mining Software Repositories},
 series = {MSR 2014},
 year = {2014},
 isbn = {978-1-4503-2863-0},
 location = {Hyderabad, India},
 pages = {192--201},
 numpages = {10},
 url = {http://doi.acm.org/10.1145/2597073.2597076},
 doi = {10.1145/2597073.2597076},
 acmid = {2597076},
 publisher = {ACM},
 address = {New York, NY, USA},
 keywords = {Code reviews, software quality},
} 
```
__Data Set:__ http://sailhome.cs.queensu.ca/replication/reviewing_quality/

**Comment by ShirinAkbari** [comment]
Title : The Impact of Code Review Coverage and Code Review
Participation on Software Quality

Email : {mcintosh, ahmed}@cs.queensu.ca 2, kamei@ait.kyushu-u.ac.jp, 3bram.adams@polymtl.ca
Abstract: Software code review, i.e., the practice of having third-party
team members critique changes to a software system, is a
well-established best practice in both open source and proprietary
software domains. Prior work has shown that the
formal code inspections of the past tend to improve the quality
of software delivered by students and small teams. However,
the formal code inspection process mandates strict review
criteria (e.g., in-person meetings and reviewer checklists)
to ensure a base level of review quality, while the modern,
lightweight code reviewing process does not. Although
recent work explores the modern code review process qualitatively,
little research quantitatively explores the relationship
between properties of the modern code review process
and software quality. Hence, in this paper, we study the
relationship between software quality and: (1) code review
coverage, i.e., the proportion of changes that have been code
reviewed, and (2) code review participation, i.e., the degree
of reviewer involvement in the code review process. Through
a case study of the Qt, VTK, and ITK projects, we find
that both code review coverage and participation share a
significant link with software quality. Low code review coverage
and participation are estimated to produce components
with up to two and five additional post-release defects
respectively. Our results empirically confirm the intuition
that poorly reviewed code has a negative impact on software
quality in large systems using modern reviewing tools.

Data link: http://sailhome.cs.queensu.ca/replication/reviewing_quality/

**Comment by reesjones** [comment]
Needs new context notes. See [this example](https://github.com/opensciences/opensciences.github.io/issues/160) or [this example](http://openscience.us/repo/issues/bugsal.html) as a reference.

Context notes are directly inserted into the actual repository (like [this](http://openscience.us/repo/issues/bugsal.html)), so good context notes are necessary for putting the datasets into the repo in a timely fashion.

**Comment by reesjones** [comment]
Added as mcintosh:
http://openscience.us/repo/other/mcintosh.html
