### ISSUE TITLE
Study Artifacts: Supporting Search and Navigation through Code Context Models

### ISSUE THREAD

**Issue by timm** [opensciences/opensciences.github.io#126]
# Email

Dear Thomas Fritz, David C. Shepherd, Katja Kevic, Will Snipes, Christoph Bräunlich

david.shepherd@us.abb.com
fritz@ifi.uzh.ch
kevic@ifi.uzh.ch
christoph.braeunlich@uzh.ch
will.snipes@us.abb.com

Thank you for placing on-line data from your paper "Developers’ Code Context Models for Change Tasks" (FSE'14).

At the suggestion of Tim Menzies, we have copied that material and added into openscience.us/repo/XXX. 

I write to ask you to check that entry. Please advise if you can see any errors there, or if you want to add some more material, or if you do not want that material on-line at openscience.us/repo . 

Thanks!
Corbin Steele
Assistant curator, 
The tera-PROMISE repository,  
openscience.us/repo
CS, NcState, USA

# URL

to paper: http://dl.acm.org/ft_gateway.cfm?id=2635905&ftid=1510839&dwn=1&CFID=463403884&CFTOKEN=90231271

to data: https://github.com/abb-iss/Study-Artifacts-for-Code-Context-Models

note that the raw git clone is 200MB which i cut in half by killing the .git as follows:

```
rm -rf `find . -type d | grep git`
```

# author emails

Thomas Fritz†
fritz@ifi.uzh.ch

David C. Shepherd*
david.shepherd@us.abb.com

Katja Kevic†
kevic@ifi.uzh.ch

Will Snipes*
will.snipes@us.abb.com

Christoph Bräunlich†
christoph.braeunlich@uzh.ch

# Context Notes
## Study Artifacts: Supporting Search and Navigation through Code Context Models

Thomas Fritz, Christoph Bräunlich, and David Shepherd conducted a study of twelve developers performing one of three change tasks using the Eclipse IDE for Java Developers. Here we publish the data collected during this study.  Our data consists of twelve transcripts of developer actions transcribed by hand from tha approximately two hours of video collected from each participant. It also includes the patches they submitted as solutions and a drawing/description of the program elements and relationships necessary to complete their task. Further details on the study setup can be found in our paper. 

[Tech Report: Supporting Search and Navigation through Code Context Models](http://www.merlin.uzh.ch/publication/show/7426)

--
### Download: 
To download our data, including transcripts, developer models, developer patches, and source code snapshots use Git to download this repository or [click on this link](https://github.com/abb-iss/Study-Artifacts-for-Code-Context-Models/archive/master.zip) for a .zip version.

--
### **Task:** [#116 New task in History->Tasks not visible](http://sourceforge.net/p/rachota/bugs/116/)
**Project:** [Rachota](http://sourceforge.net/projects/rachota/), **Version:** 2.4, **Subjects:** R1, R2, R3, R4

--
### **Task:** [Save Failed - Data Loss Occurs - ID: 3420227](http://sourceforge.net/tracker/?func=detail&aid=3420227&group_id=7118&atid=107118)
**Project:** [Freemind](http://sourceforge.net/projects/freemind/), **Version:** 0.9.0 RC 15, **Subjects:** F1, F2, F3, F4

--
### **Task:** [#30 list position lost after sleep](http://sourceforge.net/p/jpwsafe/bugs/30/)
**Project:** [JPasswordSafe](http://sourceforge.net/projects/jpwsafe/), **Version:** 2.4, **Subjects:** J1, J2, J3, J4

--
## Example Developer Packet (R3)

![Developer Model](Rachota/R3 - Developer Model.jpg)
A drawing or description of the program elements (e.g., methods, classes, fields) that the developer needed to understand in order to complete his/her task

![Transcript in Excel](Rachota/R3 - Transcript in Excel.PNG)
Transcript of developer's actions when working (partial transcript shown here, entire transcript available in repository)

    diff --git a/Rachota/src/org/cesilko/rachota/gui/HistoryView.java b/Rachota/src/org/cesilko/rachota/gui/HistoryView.java
    index 51a4d70..243c8ab 100644
    --- a/Rachota/src/org/cesilko/rachota/gui/HistoryView.java
    +++ b/Rachota/src/org/cesilko/rachota/gui/HistoryView.java
    @@ -36,6 +36,7 @@
     import java.util.Enumeration;
     import java.util.Iterator;
     import java.util.Vector;
    +
     import javax.swing.JMenuItem;
     import javax.swing.JOptionPane;
     import javax.swing.JPopupMenu;
    @@ -45,12 +46,20 @@
     import javax.swing.tree.DefaultMutableTreeNode;
     import javax.swing.tree.TreePath;
     import javax.swing.tree.TreeSelectionModel;
    +
     import org.cesilko.rachota.core.Day;
     import org.cesilko.rachota.core.Plan;
     import org.cesilko.rachota.core.Settings;
     import org.cesilko.rachota.core.Task;
     import org.cesilko.rachota.core.Translator;
    -import org.cesilko.rachota.core.filters.*;
    +import org.cesilko.rachota.core.filters.AbstractTaskFilter;
    +import org.cesilko.rachota.core.filters.DescriptionFilter;
    +import org.cesilko.rachota.core.filters.DurationFilter;
    +import org.cesilko.rachota.core.filters.IdleFilter;
    +import org.cesilko.rachota.core.filters.KeywordFilter;
    +import org.cesilko.rachota.core.filters.PriorityFilter;
    +import org.cesilko.rachota.core.filters.PrivateFilter;
    +import org.cesilko.rachota.core.filters.StateFilter;
     
     /** Panel providing history view on tasks from the past.
      * @author Jiri Kovalsky
    @@ -242,6 +251,7 @@
                         tbTasks.getColumnModel().getColumn(i).setHeaderValue(filteredTasksTableModel.getColumnName(i));
                 }
             });
    +        
         }
         
         /** Returns font that should be used for all widgets in this component
    @@ -1605,6 +1615,7 @@
             txtFilteredTime.setText(Tools.getTime(filteredTasksTableModel.getTotalTime()));
             historyChart.setDays(getDays());
             updateTotalTime();
    +        filterTasks();
         }
         
         public class MouseActionAdapter extends MouseAdapter implements ActionListener {

A patch containing developer's changes

**Comment by CarterPape** [comment]
Added as _conmodels_

http://openscience.us/repo/other/conmodels.html
