### ISSUE TITLE
Distilling privacy requirements for mobile applications

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#127]
paper:http://delivery.acm.org/10.1145/2570000/2568240/p871-thomas.pdf?ip=152.7.224.6&id=2568240&acc=ACTIVE%20SERVICE&key=6ABC8B4C00F6EE47%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&CFID=609851752&CFTOKEN=92241930&__acm__=1418931118_4c5af99db0e5e2f27494535471c6b781

dataset: see the paper in http://delivery.acm.org/10.1145/1630000/1620547/p1-mancini.pdf?ip=152.7.224.6&id=1620547&acc=ACTIVE%20SERVICE&key=6ABC8B4C00F6EE47%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&CFID=609851752&CFTOKEN=92241930&__acm__=1418931204_ffc0819138c813fd072227df95693dae

**Comment by Amoula1** [comment]
*1.  Paper Title: Distilling privacy requirements for mobile applications
* 2. Paper link: http://dl.acm.org/citation.cfm?id=2568240
* 3. Authors, emails:
 Keerthi Thoma, Arosha K. Bandara, Blaine A. Price, Bashar Nuseibe, 
{keerthi.thomas, arosha.bandara, blaine.price, bashar.nuseibeh}@open.ac.uk 
* 4. @inproceedings{Thomas:2014:DPR:2568225.2568240,
 author = {Thomas, Keerthi and Bandara, Arosha K. and Price, Blaine A. and Nuseibeh, Bashar},
 title = {Distilling Privacy Requirements for Mobile Applications},
 booktitle = {Proceedings of the 36th International Conference on Software Engineering},
 series = {ICSE 2014},
 year = {2014},
 isbn = {978-1-4503-2756-5},
 location = {Hyderabad, India},
 pages = {871--882},
 numpages = {12},
 url = {http://doi.acm.org/10.1145/2568225.2568240},
 doi = {10.1145/2568225.2568240},
 acmid = {2568240},
 publisher = {ACM},
 address = {New York, NY, USA},
 keywords = {mobile, privacy, requirements engineering},
} 
* Link to the dataset: No Link
* 6.PROMISE repo category: Requirements
* 7.  General overview of the data: 
..." this qualitative data, in the form of interview transcripts or user written reports, may contain privacy requirements that are embedded and tightly entwined with user’s contextual experiences..." , "...we explained how the qualitative data was used to highlight a privacy concern relating to the threat of sensitive data being exposed..."
9.  Abstract: 
As mobile computing applications have become commonplace, it
is increasingly important for them to address end-users’ privacy
requirements. Privacy requirements depend on a number of
contextual socio-cultural factors to which mobility adds another
level of contextual variation. However, traditional requirements
elicitation methods do not sufficiently account for contextual
factors and therefore cannot be used effectively to represent and
analyse the privacy requirements of mobile end users. On the
other hand, methods that do investigate contextual factors tend to
produce data that does not lend itself to the process of
requirements extraction. To address this problem we have
developed a Privacy Requirements Distillation approach that
employs a problem analysis framework to extract and refine
privacy requirements for mobile applications from raw data
gathered through empirical studies involving end users. Our
approach introduces privacy facets that capture patterns of privacy
concerns which are matched against the raw data. We demonstrate
and evaluate our approach using qualitative data from an
empirical study of a mobile social networking application.
