### ISSUE TITLE
XMLMate: evolutionary XML test generation

### ISSUE THREAD

**Issue by rahulpandita** [opensciences/opensciences.github.io#128]
XMLMate: evolutionary XML test generation

Link to the paper: http://dl.acm.org/citation.cfm?id=2635868.2661666&coll=DL&dl=GUIDE&CFID=464701544&CFTOKEN=55037057

Link to the Data: https://www.st.cs.uni-saarland.de/testing/xmlmate/

Nikolas Havrikov, Matthias Höschele, Juan Pablo Galeotti, Andreas Zeller
Pages: 719-722
doi>10.1145/2635868.2661666
Full text: PDFPDF

Generating system inputs satisfying complex constraints is still a challenge for modern test generators. We present XMLMATE, a search-based test generator specially aimed at XML-based systems. XMLMATE leverages program structure, existing XML schemas, ... expand
CHOReOSynt: enforcing choreography realizability in the future internet

**Comment by timm** [comment]
# Context notes

## Contents

Zip file (46M) divides as follows:

```
.
├── batik
│   ├── evosuite-tests
│   ├── microsoft-xmlsamplegenerator
│   ├── msv
│   ├── samples
│   ├── test_driver
│   ├── xmlmate(random)
│   └── xmlmate(samples)
├── flyingsaucer
│   ├── evosuite-tests
│   ├── microsoft-xmlsamplegenerator
│   ├── samples
│   ├── test_driver
│   ├── xmlmate(random)
│   └── xmlmate(samples)
├── freedots
│   ├── evosuite-tests
│   ├── microsoft-xmlsamplegenerator
│   ├── msv
│   ├── samples
│   ├── test_driver
│   ├── xmlmate(random)
│   └── xmlmate(samples)
├── jeuclid
│   ├── evosuite-tests
│   ├── samples
│   ├── test_driver
│   ├── xmlmate(random)
│   └── xmlmate(samples)
├── rome
│   ├── evosuite-tests
│   ├── microsoft-xmlsamplegenerator
│   ├── msv
│   ├── samples
│   ├── test_driver
│   ├── xmlmate(random)
│   └── xmlmate(samples)
├── svgimage
│   ├── evosuite-tests
│   ├── microsoft-xmlsamplegenerator
│   ├── msv
│   ├── samples
│   ├── test_driver
│   ├── xmlmate(random)
│   └── xmlmate(samples)
└── svgsalamander
    ├── evosuite-tests
    ├── microsoft-xmlsamplegenerator
    ├── msv
    ├── samples
    ├── test_driver
    ├── xmlmate(random)
    └── xmlmate(samples)
```

**Comment by CarterPape** [comment]
Email: zeller@st.cs.uni-saarland.de

**Comment by reesjones** [comment]
Added as xmlmate.
http://openscience.us/repo/other/xmlmate.html
