### ISSUE TITLE
RaPiD: a toolkit for reliability analysis of non-deterministic systems

### ISSUE THREAD

**Issue by rahulpandita** [opensciences/opensciences.github.io#130]
## RaPiD: a toolkit for reliability analysis of non-deterministic systems

Link to paper: http://dl.acm.org/citation.cfm?id=2635868.2661668&coll=DL&dl=GUIDE&CFID=464701544&CFTOKEN=55037057

Link to Data: http://www.comp.nus.edu.sg/~a0068192/ResearchWork/RaPiD.html

Lin Gui, Jun Sun, Yang Liu, Truong Khanh Nguyen, Jin Song Dong
Pages: 727-730
doi>10.1145/2635868.2661668
Full text: PDFPDF

Non-determinism in concurrent or distributed software systems (i.e., various possible execution orders among different distributed components) presents new challenges to the existing reliability analysis methods based on Markov chains. In this work, ... expand

**Comment by rahlk** [comment]
ToolKit
