### ISSUE TITLE
Critics: an interactive code review tool for searching and inspecting systematic changes

### ISSUE THREAD

**Issue by rahulpandita** [opensciences/opensciences.github.io#133]
## Critics: an interactive code review tool for searching and inspecting systematic changes

Link to paper : http://dl.acm.org/citation.cfm?id=2635868.2661675&coll=DL&dl=GUIDE&CFID=464701544&CFTOKEN=55037057

Link to Data : https://sites.google.com/a/utexas.edu/critics/download

### Notes: 
The oracle test suite are seven groups of systematic changes, drawn from Eclipse.JDT and Eclipse.SWT.
Download data here - https://www.dropbox.com/s/nf4m7es1v8vqleb/DataSet.zip?dl=1

### Contact:
Please contact [Tianyi Zhang](mailto:troyathust@gmail.com)

**Comment by timm** [comment]
This one looks cool enough to justify including. So write context notes and add links to the 350MB data.

**Comment by reesjones** [comment]
Needs new context notes. See [this example](https://github.com/opensciences/opensciences.github.io/issues/160) or [this example](http://openscience.us/repo/issues/bugsal.html) as a reference.

Context notes are directly inserted into the actual repository (like [this](http://openscience.us/repo/issues/bugsal.html)), so good context notes are necessary for putting the datasets into the repo in a timely fashion.

**Comment by rahlk** [comment]
Just some toolkits, no useable data found.
