### ISSUE TITLE
ISSRE(W) '14 Chunk #3

### ISSUE THREAD

**Issue by BenProvince** [opensciences/opensciences.github.io#135]
# Category: Testing 1

## Soft-LLFI; A Comprehensive Framework for Software Fault Injection
Maryam Raiyat Aliabadi, Karthik Pattabiraman and Nematollah Bidokhti
pages:1-5
doi>10.1109/ISSREW.2014.114

This paper makes the following contributions to the current state of the art: to propose 1) a comprehensive reference of software fault models faithfully representing a wide spectrum of investigated software bugs in real applications, and 2) a robust configurable SFI architecture to automate injection of software fault model of appropriate type, and to visualize impact analysis.

vivekaxl: no data

## Fault Injection Experiments With the CLAMR Hydrodynamics Mini-App
Brian Atkinson, Nathan Debardeleben, Qiang Guan, Robert Robey and William Jones
pages: 6-9
doi>10.1109/ISSREW.2014.51

In this paper, we present a resilience analysis of the impact of soft errors on CLAMR, a hydrodynamics mini-app for high performance computing (HPC). We utilize F-SEFI, a fine grainedfault injection tool, to inject faults into the kernel routines of CLAMR. We demonstrate visually the impact of these faults as they are either benign (have no impact on the results), cause silent data corruption (SDC), or cause the application to crash due to instabilities.

vivekaxl: no data

## Event Logging in an Industrial Development Process: Practices and Reengineering Challenges
Fabio Baccanico, Gabriella Carrozza, Marcello Cinque, Domenico Cotroneo, Antonio Pecchia and Agostino Savignano
pages: 10-13
doi>10.1109/ISSREW.2014.69

The analysis aims to support log reengineering activities that are currently conducted at SELEX ES. At time being, some of the issues described in the paper have been fixed by system developers. Analysis encompasses total around 50+ millions lines of log produced by an Air Traffic Control (ATC) system.

vivekaxl: no data

# Category: Reliability Modeling 1

## Event Based Robot Prognostics using Principal Component Analysis
Sathish V, Sudarsan S.D and Srini Ramaswamy. 
pages: 14-17
doi>10.1109/ISSREW.2014.52

In this paper, we provide a Principal component Analysis (PCA) based approach of failure prediction in industrial robots using event log information. The event logs are collected through remote service set-up from a robot controller. 

vivekaxl: no data

##  Proving Model Equivalence in Model Based Design
Ashlie Hocking, John Knight, Anthony Aiello and Shin’ichi Shiraishi
pages: 18-21
doi>10.1109/ISSREW.2014.83

We introduce the concept of constrained equivalence of models in model-based development and present a proof technology for establishing constrained equivalence for models documented in Math Works Simulink. We illustrate the approach using a simple model of an automobile anti-lock braking system.

vivekaxl: no data

##  Developing Software Reliability Models in the Architecture Phase of the Software Lifecycle
 Alberto Avritzer and Andre Bondi
pages: 22-23
doi>10.1109/ISSREW.2014.110

We present an approach for software reliability modeling at the architecture phase that has been applied to a large complex industrial system. The practicality of the approach is supported by the ease of use and model simplicity, which followed from the failure data analysis and the system architecture workflow modeling of this large and complex industrial system.

vivekaxl: no data

# Section: Testing 2

## Architecture for a hard-real-time system enabling non-intrusive tests
Joachim Froehlich and Reiner Schmid
pages: 3-6
doi>10.1109/ISSREW.2014.140

[No abstract]

vivekaxl: I can't find the paper online. There is a presentation available. No data there

## Handling Soft Error in Embedded Software for Networking System
Haihong Henry Zhu
pages: 25-28
doi>10.1109/ISSREW.2014.109

This paper presents a comprehensive framework for single-event upset (SEU) mitigation methodologies for networking system. To achieve this goal we start by defining the SEU mitigation strategy as a combination of chip level methods and system level handling methods. 

vivekaxl: no data

## Safety Critical Robot Programming and Testing for Operations in Industrial Co-production
Linn Gustavsson Christiernin, Svante Augustsson and Stefan Christiernin
pages: 29-32
doi>10.1109/ISSREW.2014.46

vivekaxl: no data

# Category: Best Paper Nominees

## Programming with Contracts - Ada 2012 Tool-Supported Industrial Insights
Quentin Ochem
pages:
doi>

[Could not find paper]

## NAPOLI FUTURA: Novel Approaches for Protecting Critical Infrastructures from Cyber Attacks
Marcello Cinque, Antonio Pecchia, Raffaele Della Corte, Agostino Savignano, Stefano Avallone, Antonio Marotta and Gabriella Carrozza
pages: 33-36
doi>10.1109/ISSREW.2014.53

The paper focuses on the architectural design of the NAPOLI FUTURA platform. The platform leverages cutting-edge big data analytics solutions to detect security attacks and to support live migration of services in the context of Critical Information Infrastructures (CIIs).

vivekaxl: no data found

## Network Function Virtualization: Challenges and Directions for Reliability Assurance
Luigi De Simone, Antonio Ken Iannillo, Anna Lanzaro, Roberto Natella, Domenico Cotroneo, Jiang Fan and Wang Ping
pages:37-42
doi>10.1109/ISSREW.2014.48

In this paper, we discuss the challenges for reliability in NFVIs, and present an industrial research project on their reliability assurance, which aims at developing novel fault injection technologies and systematic guidelines for this purpose.

# Category: Availability and Performance

## Towards an Evaluation Framework for Availability Solutions in the Cloud
Majid Hormati, Ferhat Khendek and Maria Toeroe
pages: 43-46
doi>10.1109/ISSREW.2014.50

We determine the different aspects that should be taken into account for protecting services in the Cloud and therefore for evaluating potential solutions. We put this framework into practice, we investigate and evaluate a set of availability solutions based on the existing Cloud and availability related components, including Open Stack, VM ware technologies and OpenSAF.

vivekaxl: couldn't find the paper

## Verifying Response Times in Networked Automation Systems Using Jitter Bounds
Seshadhri Srinivasan, Furio Buonopane, Srini Ramaswamy and Juri Vain
pages: 47-50
doi>10.1109/ISSREW.2014.42

This investigation uses model templates for verifying the response time in NAS. First, jitter bounds model the timing fluctuations of NAS components. These jitter bounds are the inputs to model templates that are formal models of timing fluctuations. The model templates are atomic action patterns composed of three composition operators-sequential, alternative, and parallel and embedded in time wrapper that specifies clock driven activation conditions. Model templates in conjunction with formal model of technical process offer an easier way to verify the response time. The investigation demonstrates the proposed verification method using an industrial steam boiler with typical NAS components in plant floor.

vivekaxl: no data found

## Balanced Measurement Sets: Criteria for Improving Project Management Practices
Fulvio Frati, Ernesto Damiani, Luigi Buglione, Daniele Gagliardi, Sergio Oltolina and Gabriele Ruffatti
pages: 82-85
doi>10.1109/ISSREW.2014.76

In this paper, we cope with this problem proposing a methodology that can allow an early adoption of balanced measurement sets, which will be iteratively refined at each iteration of the process. The proposed methodology can be implemented and supported by open source tools like the Spago4Q platform.

vivekaxl: No data found

# Category: Reliability Modeling 2

## Using Data Analytics to Drive Product Software Reliability
Veena Mendiratta and Robert Hanmer
pages:
doi>

[could not find paper]
vivekaxl: I agree

## Reliability Models for the Internet of Things: A Paradigm Shift
Mudasir Ahmad
pages: 52-59
doi>10.1109/ISSREW.2014.107

An analytical framework is outlined to capture the asynchronous variation of software upgrades with hardware changes. The models developed can then be used to perform sensitivity studies to determine which factors are most influential in degrading reliability, and rank ordering them.

vivekaxl: no data found.

## Predicting Release Quality
Pete Rotella and Sunita Chulani
pages: 60-61
doi>10.1109/ISSREW.2014.116

In this paper we will show correlations with SWDPMH of feature release sequences for 16 product families. We will also show the models' applicability to maintenance release sequences, features, and Business Unit contributions to feature releases. We will also show - he models' performance characteristics with agile releases, hybrid agile/waterfall releases, and traditional waterfall releases.

vivekaxl: no data. I didn't find the whole paper, just some sort of a write up in http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6983802

**Comment by Windy-with-sky** [comment]
Is there any code here，Controlled Channel aCCess for Ieee 802.11-Based WIreless tsn netWorks
