### ISSUE TITLE
 Estimating development effort in Free/Open source software projects by mining software repositories: a case study of OpenStack

### ISSUE THREAD

**Issue by CorbinSteele** [opensciences/opensciences.github.io#136]
### Paper Link:
http://dl.acm.org/citation.cfm?id=2597107
### Replication Package:
http://gsyc.urjc.es/~grex/repro/2014-msr-effort

**Comment by BenProvince** [comment]
#Context Notes:
There are two types of data associated with this paper: author activity from OpenStack contributors and survey data from the contributors.

## Author Activity Data
-Rows represent individual authors (1626 total)
-Columns represent months starting in Jan 2010 (these are 0-padded before and after project)
-The actual author IDs can be found by cross-referencing output_author_ids_nobots.csv:
    http://gsyc.urjc.es/~grex/repro/2014-msr-effort/output_authors_ids_nobots.csv
-Number of commits per month: 
    http://gsyc.urjc.es/~grex/repro/2014-msr-effort/output_commits_nobots.csv
-Number of active days per month:
    http://gsyc.urjc.es/~grex/repro/2014-msr-effort/output_activity_nobots.csv

##Survey Response Data
This represents voluntary responses to a survey in which 131 individuals responded.
Survey questions are as follows:

1) Selection: On average, how many hours in a week have you spent in the project in the last six months?
(>40h, 40h, 30h, 20h, 10h, <5h)

2) Selection: How much of the time you spent in the project is devoted to coding? 
(>95%, approx. 75%, approx. 50%, approx. 25%, <10%)

3) Selection: Do you make at least one commit to the repository the days you code? 
(yes, no)

4) Selection: What do you consider yourself in the project? 
(full-time, part-time, occasional contributor)

5) Free-text box: Did you always work on the project the same amount of hours, or did you have different phases of commitment? If you had different phases, could you tell us about the various phases? (the graph below may help you, as it is based in your recorded activity in the repository)

The survey data has 4 columns which reflect questions 1-4 and two additional columns labeled "info" and "survey" **of which I can't seem to find a description.**

The original (anonymized) survey response data is here:
http://gsyc.urjc.es/~grex/repro/2014-msr-effort/answers_openstack.all.public.csv

This survey data was cleaned with a few respondents being removed and some responses being edited. A description of the cleaning process as well as the cleaned response data is here:
http://gsyc.urjc.es/~grex/repro/2014-msr-effort/survey_cleaning.txt
http://gsyc.urjc.es/~grex/repro/2014-msr-effort/answers_openstack.public.csv

**Comment by CarterPape** [comment]
Added as *openeffort*

http://openscience.us/repo/effort/other-effort/openeffort.html
