### ISSUE TITLE
It's not a bug, it's a feature: does misclassification affect bug localization?

### ISSUE THREAD

**Issue by CorbinSteele** [opensciences/opensciences.github.io#142]
### Notes
__Categorization:__ Other
__Authors:__ [Pavneet Singh Kochhar](mailto:kochharps.2012@smu.edu.sg),  [Tien-Duy B. Le](mailto:btdle.2012@smu.edu.sg), and [David Lo](mailto:davidlo@smu.edu.sg)
__General overview of the data:__

They download Herzig et al.'s datasets which  included the  identiers  of  issue  reports  that  they have  manually  analyzed. The description of that dataset follows.

The authors conducted a study on five open-source JAVA projects described in Table I (see [paper](https://www.st.cs.uni-saarland.de/softevo/bugclassify/paper/icse2013-bugclassify.pdf)). They aimed to select  projects  that  were under  active  development  and  were  developed  by  teams  that follow strict commit and bug fixing procedures similar to industry. They also aimed to have a more or less homogenous data set  which  eased  the  manual  inspection  phase.  Projects  from APACHE and MOZILLA seemed to fit their requirements best. Additionally, they selected the five projects such that they cover atleast two different and popular bug tracking systems: Bugzilla1 and  Jira2. Three out of five projects (Lucene-Java, Jackrabbit,and  HTTPClient)  use  a  Jira  bug  tracker.  The  remaining  two projects (Rhino, Tomcat5) use a Bugzilla tracker. For  each  of  the  five  projects,  they  selected  all  issue  reports  that  were  marked  as  being RESOLVED , CLOSED,  or VERIFIED and  whose  resolution  was  set  to FIXED and performed a manual inspection on these issues. They  disregarded issues  with  resolution  in  progress  or  not  being  accepted,  as their features may change in the future.The  number  of  inspected  reports  per  project  can  be  found in the table above. In total, they obtained 7,401 closed and fixed issue reports.  1,810  of  these  reports  originate  from  the  Rhino  and Tomcat5  projects  and  represent  Bugzilla  issue  reports.  The remaining of the 5,591 reports were filed in a Jira bug tracker.
__Link:__ [It's not a bug, it's a feature: does misclassification affect bug localization?](http://dl.acm.org/citation.cfm?id=2597105)
__Bibtex:__ 
```tex
@inproceedings{Kochhar:2014:BFM:2597073.2597105,
 author = {Kochhar, Pavneet Singh and Le, Tien-Duy B. and Lo, David},
 title = {It's Not a Bug, It's a Feature: Does Misclassification Affect Bug Localization?},
 booktitle = {Proceedings of the 11th Working Conference on Mining Software Repositories},
 series = {MSR 2014},
 year = {2014},
 isbn = {978-1-4503-2863-0},
 location = {Hyderabad, India},
 pages = {296--299},
 numpages = {4},
 url = {http://doi.acm.org/10.1145/2597073.2597105},
 doi = {10.1145/2597073.2597105},
 acmid = {2597105},
 publisher = {ACM},
 address = {New York, NY, USA},
 keywords = {Bug Localization, Misclassification},
} 
```
__Data Set:__ 
+ https://www.st.cs.uni-saarland.de/softevo/bugclassify/data/httpclient_classification_vs_type.csv
+ https://www.st.cs.uni-saarland.de/softevo/bugclassify/data/jackrabbit_classification_vs_type.csv
+ https://www.st.cs.uni-saarland.de/softevo/bugclassify/data/lucene_classification_vs_type.csv
+ https://www.st.cs.uni-saarland.de/softevo/bugclassify/data/rhino_classification_vs_type.csv
+ https://www.st.cs.uni-saarland.de/softevo/bugclassify/data/tomcat5_classification_vs_type.csv

**Comment by reesjones** [comment]
Needs new context notes. See [this example](https://github.com/opensciences/opensciences.github.io/issues/160) or [this example](http://openscience.us/repo/issues/bugsal.html) as a reference.

Context notes are directly inserted into the actual repository (like [this](http://openscience.us/repo/issues/bugsal.html)), so good context notes are necessary for putting the datasets into the repo in a timely fashion.

**Comment by reesjones** [comment]
Added as bugclassify.
http://openscience.us/repo/other/bugclassify.html
