### ISSUE TITLE
Scaling Exact Multi-Objective Combinatorial Optimization by Parallelization

### ISSUE THREAD

**Issue by nave91** [opensciences/opensciences.github.io#146]
paper link: http://dl.acm.org/citation.cfm?id=2642971&CFID=609852226&CFTOKEN=49731104

data link: http://www.splot-research.org/

**Comment by timm** [comment]
## heading

+ dot1
+ dot2

asda _italic_ asdas

**Comment by timm** [comment]
# Context Notes

## Download Models From

[http://www.splot-research.org/]( http://www.splot-research.org/)

**Comment by Amoula1** [comment]
Summary

**Comment by reesjones** [comment]
Needs new context notes. See [this example](https://github.com/opensciences/opensciences.github.io/issues/160) or [this example](http://openscience.us/repo/issues/bugsal.html) as a reference.

Context notes are directly inserted into the actual repository (like [this](http://openscience.us/repo/issues/bugsal.html)), so good context notes are necessary for putting the datasets into the repo in a timely fashion.

**Comment by WeiFoo** [comment]
Categorization (effort, requirements, model, defect, etc.)
    If it doesn't fit nicely into one of these categories, put "other" and propose a category name
    Pick from the categories in the navbar on the OpenScience website.

Author list for the paper (including emails)

General overview of the data
    Note that this is not the abstract of the paper. If you can find an overview of the dataset in the author's own words, just copy those words. If not, make your own overview. Paragraph long (if you are making it yourself)

Link to the paper associated with the dataset
    This should be either a link to the ACM digital library (e.g. http://dl.acm.org/citation.cfm?id=2635868.2635905), IEEE digital library (e.g. http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6982619), or some other standard library

Paper abstract

BibTeX reference for the paper

Link to the datasets
    If multiple files come with it, include links to all files, not just the parent file
    Red flags should go up if, after downloading all the data, it is larger than 100 MB (compressed)

Is this dataset part of a larger series or collection?
    If so, link to the master index of the series or collection (if possible)

**Comment by reesjones** [comment]
Added as splot.
http://openscience.us/repo/model/splot.html
