### ISSUE TITLE
Predicting Effectiveness of IR-Based Bug Localization Techniques

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#148]
Paper: Predicting Effectiveness of IR-Based Bug Localization Techniques
Data: The paper has used publicly available data. Should this be included. " We conduct experiments using three sets of bug reports from AspectJ, Eclipse, and SWT which contain a total of more than three thousands bug reports"

**Comment by timm** [comment]
![image](https://cloud.githubusercontent.com/assets/29195/6193897/7ef67c78-b38d-11e4-8a98-07f6c42d3ec0.png)

**Comment by Amoula1** [comment]
**Title: Predicting Effectiveness of IR-Based Bug Localization Techniques
**Author, email: 
Tien-Duy B. Le, btdle.2012@smu.edu.sg
Ferdian Thung, ferdiant.2013@smu.edu.sg  
David Lo, davidlo@smu.edu.sg

** Main Objective: Addressing the unreliability of Information Retrieval (IR)-based bug localization techniques.
**Main Contribution:Proposition of an approach named APRILE, which stands for Automated PRediction of IR-based Bug Localization’s Effectiveness. APRILE can automatically predict whether a ranked list produced by an Information Retrieval (IR)-based bug localization tool is likely to be effective or not.
**Evaluation results 
We have evaluated APRILE to predict the effectiveness of three state-of-the-art IRbased bug localization tools on more than three thousands bug reports from AspectJ, Eclipse, and SWT. APRILE can achieve an average precision, recall, and F-measure of at least 70.36%, 66.94%, and 68.03%, respectively. APRILE outperforms a baseline approach by 84.48%, 17.74%, and 31.56%
for the AspectJ, Eclipse, and SWT bug reports, respectively.

**Datasets: Use of three sets of bug reports from AspectJ, SWT and Eclipse.
Dataset summary:
1) Project name : AspectJ
Study period: Jul 2002 - Oct 2006 286 6485
# Bugs: 286
#Files: 6485
2) Project name: Eclipse (3.1) 
Study period: Oct 2004 - Mar 2011 
#Bugs: 3075 
#Files: 12863
3) Project name: SWT (3.1)
#Bugs: 98
#Files: 6485

**Comment by Amoula1** [comment]
Link of the paper: http://sci-hub.org/downloads/5ad1/10.0000@www.researchgate.net@266141214.pdf

**Comment by Amoula1** [comment]
For the datasets, finding them here is a difficult process since there is no link provided. Thus, it would be easier to find the same datasets used from another paper ;)
