### ISSUE TITLE
Why Does my Spreadsheet Compute Wrong Values?

### ISSUE THREAD

**Issue by rahulpandita** [opensciences/opensciences.github.io#152]
## Why Does my Spreadsheet Compute Wrong Values?

Paper Url: http://ieeexplore.ieee.org/xpl/articleDetails.jsp?tp=&arnumber=6982619&queryText%3DWhy+Does+my+Spreadsheet+Compute+Wrong+Values%3F
Data url : https://dl.dropbox.com/u/38372651/Spreadsheets/Integer_Spreadsheets.zip

---
Franz Wotawa and Birgit Hofer
pages: 112-121
doi>10.1109/ISSRE.2014.23

In this paper, we introduce a novel dependency-based approach for model-based fault localization in spreadsheets. This approach improves diagnostic accuracy while keeping computation times short, thus making the automated fault localization more appropriate for practical applications.

**Comment by reesjones** [comment]
The provided data should be included as a whole.
We've not found any context files about what the data actually is.

**Comment by CarterPape** [comment]
Why does this paper (http://ceur-ws.org/Vol-1209/paper_5.pdf) look so similar?

**Comment by reesjones** [comment]
## Authors

 * Birgit hofer, [bhofer@ist.tugraz.at](mailto:bhofer@ist.tugraz.at)
 * Franz Wotawa, [wotawa@ist.tugraz.at](mailto:wotawa@ist.tugraz.at)

## Paper & data

Paper: [link](http://ieeexplore.ieee.org/xpl/articleDetails.jsp?tp=&arnumber=6982619&queryText%3DWhy+Does+my+Spreadsheet+Compute+Wrong+Values%3F)
Data: [link](https://dl.dropbox.com/u/38372651/Spreadsheets/Integer_Spreadsheets.zip)


## Abstract

> Spreadsheets are by far the most used programs
> that are written by end-users. They often build the basis for decisions
> in companies and governmental organizations and therefore
> they have a high impact on our daily life. Ensuring correctness
> of spreadsheets is thus an important task. But what happens
> after detecting a faulty behavior? This question has not been
> sufficiently answered. Therefore, we focus on fault localization
> techniques for spreadsheets. In this paper, we introduce a novel
> dependency-based approach for model-based fault localization in
> spreadsheets. This approach improves diagnostic accuracy while
> keeping computation times short, thus making the automated
> fault localization more appropriate for practical applications. The
> presented approach allows for an acceptable fault localization
> time of less than a second, and reduces the number of computed
> root cause candidates by 15% on average, when compared with
> another dependency-based approach.


## Data

This dataset contains 33 different spreadsheets (12 artificially created
spreadsheets and 21 real-life spreadsheets) and . These spreadsheets contain 
both arithmetical and logical operators as well as the functions SUM and 
IF. Faulty versions of the spreadsheets (containing single, double and 
triple faults) were created by randomly selecting formulas and applying
mutation operators [31] on them.

**Comment by timm** [comment]
I need to contact Burnett re getting more samples.

**Comment by reesjones** [comment]
Description added to repo

**Comment by reesjones** [comment]
Added as faultsfw.
http://openscience.us/repo/spreadsheet/faultsfw.html
