### ISSUE TITLE
ining Energy-Greedy API Usage Patterns in Android Apps: An Empirical Study

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#153]
paper link :http://dl.acm.org/ft_gateway.cfm?id=2597085&ftid=1467091&dwn=1&CFID=626462430&CFTOKEN=89002593

data link: reference[26]http://www.cs.wm.edu/semeru/data/MSR14-android-energy/

**Comment by rahlk** [comment]
Insignificant data
