### ISSUE TITLE
Works For Me! Characterizing Non-reproducible Bug Reports

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#158]
paper link:http://dl.acm.org/citation.cfm?id=2597098&CFID=626469285&CFTOKEN=55193119

datasets:https://github.com/saltlab/NR-bug-analyzer

Context Notes: {merfani, mehdi, amesbah}@ece.ubc.ca

**Comment by reesjones** [comment]
Needs new context notes. See [this example](https://github.com/opensciences/opensciences.github.io/issues/160) or [this example](http://openscience.us/repo/issues/bugsal.html) as a reference.

Context notes are directly inserted into the actual repository (like [this](http://openscience.us/repo/issues/bugsal.html)), so good context notes are necessary for putting the datasets into the repo in a timely fashion.

**Comment by WeiFoo** [comment]
**Categorization**
   other: bug report

**Author list for the paper (including emails)**

Mona Erfani Joorabchi: merfani@ece.ubc.ca
Mehdi Mirzaaghaei: mehdi@ece.ubc.ca
Ali Mesbah: amesbah@ece.ubc.ca

**General overview of the data**

To ensure representativeness, there're five popular, actively maintained software projects from three separate domains, namely desktop (Firefox and Eclipse), web
(MediaWiki and Moodle), and mobile (Firefox Android). In addition, one commercial closed source application (Industrial) is included. The proprietary bug tracking system is from a Vancouver-based mobile app development company. The bug reports are filed by their testing team and end-users, and are related to different mobile platforms such as An- droid, Blackberry, iOS, and Windows Phone, as well as their content management platform and backend software.

**Link to the paper associated with the dataset**

http://dl.acm.org/citation.cfm?id=2597098&CFID=626469285&CFTOKEN=55193119

**Paper abstract**
Bug repository systems have become an integral component of software development activities. Ideally, each bug report should help developers to find and fix a software fault. How- ever, there is a subset of reported bugs that is not (easily) re- producible, on which developers spend considerable amounts of time and effort. We present an empirical analysis of non- reproducible bug reports to characterize their rate, nature, and root causes. We mine one industrial and five open- source bug repositories, resulting in 32K non-reproducible bug reports. We (1) compare properties of non-reproducible reports with their counterparts such as active time and num- ber of authors, (2) investigate their life-cycle patterns, and (3) examine 120 Fixed non-reproducible reports. In addi- tion, we qualitatively classify a set of randomly selected non-reproducible bug reports (1,643) into six common cate- gories. Our results show that, on average, non-reproducible bug reports pertain to 17% of all bug reports, remain active three months longer than their counterparts, can be mainly (45%) classified as “Interbug Dependencies”, and 66% of Fixed non-reproducible reports were indeed reproduced and fixed.

**BibTeX reference for the paper**

@inproceedings{erfani2014works,
  title={Works for me! Characterizing non-reproducible bug reports},
  author={Erfani Joorabchi, Mona and Mirzaaghaei, Mehdi and Mesbah, Ali},
  booktitle={Proceedings of the 11th Working Conference on Mining Software Repositories},
  pages={62--71},
  year={2014},
  organization={ACM}
}

**Link to the datasets**
   https://github.com/saltlab/NR-bug-analyzer/tree/master/Data

Is this dataset part of a larger series or collection?
   no

**Comment by reesjones** [comment]
Added as mebug.
http://openscience.us/repo/other/mebug.html
