### ISSUE TITLE
[ISSRE'2014] Quantitative Evaluation of Static Analysis Tools

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#164]
Abstract: —This paper presents a quantitative comparison of
static analysis tools. First, we conduct a wide-ranging survey of
static analysis tools and select several promising tools qualitatively.
Second, we build test suites that contain a large variety of
defects and evaluate the selected tools with them. Third, we derive
several metrics for measuring tool performance and subsequently
clarify the characteristics of the said tools by using them. Finally,
we quantitatively identify the best tools from several different
viewpoints

To evaluate the performance of the selected static analysis tools, we need to create test suites wherein several defects are implemented intentionally.

The test suites can be found in https://github.com/regehr/itc-benchmarks

Authors emails: 
sshiraishi@us.toyota-itc.com, vmohan@us.toyota-itc.com, hmarimuthu@us.toyota-itc.com

**Comment by timm** [comment]
# there is a widnow here

this is _some text_

+  abd here is a dot oint

**Comment by reesjones** [comment]
Needs new context notes. See [this example](https://github.com/opensciences/opensciences.github.io/issues/156) or [this example](http://openscience.us/repo/issues/bugsal.html) as a reference.

Context notes are directly inserted into the actual repository (like [this](http://openscience.us/repo/issues/bugsal.html)), so good context notes are necessary for putting the datasets into the repo in a timely fashion.

**Comment by WeiFoo** [comment]
Where is data .......?
