### ISSUE TITLE
An empirical study of just-in-time defect prediction using cross-project models

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#166]
paper link:http://dl.acm.org/ft_gateway.cfm?id=2597075&ftid=1467103&dwn=1&CFID=626469285&CFTOKEN=55193119

dataset: please go to see this paper __A large-scale empirical study of just-in-time quality assurance__

**Comment by twinitialize** [comment]
Too big.

Mozilla and Bugzilla: http://msr.uwaterloo.ca/msr2007/challenge/index.html - see **Data** section.

Eclipse JDT and Eclipse Platform data: - http://msr.uwaterloo.ca/msr2008/challenge/index.html - see **Data** section.

Columba: https://hal.archives-ouvertes.fr/hal-00769121/file/cvs-vintage-light-v20120509.tar.bz2

PostgreSQL - not sure.

**Comment by timm** [comment]
This data is important enough for us to collect.  So I'm culling the "too big" tag and going back to "collect"

**Comment by BenProvince** [comment]
As twinitialize said, Mozilla and Bugzilla can be obtained from 2007 MSR:
http://msr.uwaterloo.ca/msr2007/challenge/index.html 

Eclipse JDT and Eclipse Platform data comes from 2008 MSR:
http://msr.uwaterloo.ca/msr2008/challenge/index.html

Columbia can be obtained at 
https://hal.archives-ouvertes.fr/hal-00769121/file/cvs-vintage-light-v20120509.tar.bz2
or at 
rsync://columba.cvs.sourceforge.net/cvsroot/columba/

PostgreSQL is *supposedly* available through rsync, though I couldn't get a response:
rsync://anoncvs.postgresql.org/cvsroot/pgsql/

The paper also says that the authors collected data from Gimp, Maven-2, Perl, Ruby on Rails, and Rhino. These are open-source projects, so data could be re-collected, but the authors did not provide datasets.

**Comment by vivekaxl** [comment]
**1. Data source**
An Empirical Study of Just-in-Time Defect Prediction using Cross-Project Models
**2. Link to the material associated with the dataset (if available)**
Examples:
http://posl.ait.kyushu-u.ac.jp/~kamei/publications/Fukushima_MSR2014.pdf
**3. Attribution list for the material**
Takafumi Fukushima, Yasutaka Kamei, Shane McIntosh, Kazuhiro Yamashita, and Naoyasu Ubayashi
f.taka@posl.ait.kyushu-u.ac.jp,
yamashita@posl.ait.kyushu-u.ac.jp, 
kamei@ait.kyushu-u.ac.jp,
ubayashi@ait.kyushu-u.ac.jp, 
mcintosh@cs.queensu.ca

**4. BibTeX reference**
@inproceedings{fukushima2014empirical,
  title={An empirical study of just-in-time defect prediction using cross-project models},
  author={Fukushima, Takafumi and Kamei, Yasutaka and McIntosh, Shane and Yamashita, Kazuhiro and Ubayashi, Naoyasu},
  booktitle={Proceedings of the 11th Working Conference on Mining Software Repositories},
  pages={172--181},
  year={2014},
  organization={ACM}
}
**5. Link to the datasets**

Eclipse CVS repository:
JDT: [eclipse-cvs-jdt.tgz](http://www.st.cs.uni-sb.de/softevo/challenge2007/eclipse-cvs-jdt.tgz) (1.10G, retrieved on 2006-11-25)
SWT: [eclipse-cvs-swt.tgz](http://www.st.cs.uni-sb.de/softevo/challenge2007/eclipse-cvs-swt.tgz) (488M, retrieved on 2006-11-25)
Rest: [eclipse-cvs-rest.tgz](http://www.st.cs.uni-sb.de/softevo/challenge2007/eclipse-cvs-rest.tgz) (1.82G, retrieved on 2006-11-25)

Eclipse Bugzilla export (in XML):
Bugs: [1-162656: eclipse-bugs.zip](http://www.st.cs.uni-sb.de/softevo/challenge2007/eclipse-bugs.zip) (125M, retrieved on 2006-10-30)
Firefox/Mozilla CVS repository: [mozilla-cvs.tgz](http://www.st.cs.uni-sb.de/softevo/challenge2007/mozilla-cvs.tgz) (609M, retrieved on 2006-12-17)
Firefox/Mozilla Bugzilla export (in XML):
Bugs 35-100000: [mozilla-bugs-000001-100000.zip](http://www.st.cs.uni-sb.de/softevo/challenge2007/mozilla-bugs-000001-100000.zip) (886M, retrieved on 2007-01-06)
Bugs 100001-200000: [mozilla-bugs-100001-200000.zip](http://www.st.cs.uni-sb.de/softevo/challenge2007/mozilla-bugs-100001-200000.zip) (1.10G, retrieved on 2007-01-06)
Bugs 200001-300000: [mozilla-bugs-200001-300000.zip](http://www.st.cs.uni-sb.de/softevo/challenge2007/mozilla-bugs-200001-300000.zip) (1.00G, retrieved on 2007-01-06)
Bugs 300001-366112: [mozilla-bugs-300001-367500.zip](http://www.st.cs.uni-sb.de/softevo/challenge2007/mozilla-bugs-300001-367500.zip) (724M, retrieved on 2007-01-06)

Eclipse CVS repository in TARE format:
[eclipse-tare.tgz](http://www.st.cs.uni-sb.de/softevo/challenge2007/eclipse-tare.tgz) (247M, retrieved by Tom Zimmermann on 2006-11-25)
Eclipse Bug Data (more details):
[eclipse-bug-data-1.1a.zip](http://www.st.cs.uni-sb.de/softevo/bug-data/eclipse/eclipse-bug-data-1.1a.zip) (920K, retrieved by Adrian Schröter)

Eclipse CVS repository:
JDT: [eclipse-cvs-jdt.tgz](http://pag.csail.mit.edu/msr_challenge2008/eclipse-cvs-jdt.tgz) (1.1G, retrieved on 2007-12-19 by Thomas Zimmermann)
SWT: [eclipse-cvs-swt.tgz](http://pag.csail.mit.edu/msr_challenge2008/eclipse-cvs-swt.tgz) (686M, retrieved on 2007-12-19 by Thomas Zimmermann)
Platform: [eclipse-cvs-plarform.tgz](http://pag.csail.mit.edu/msr_challenge2008/eclipse-cvs-platform.tgz) (686M, retrieved on 2007-12-19 by Thomas Zimmermann)
Rest: [eclipse-cvs-rest.tgz](http://pag.csail.mit.edu/msr_challenge2008/eclipse-cvs-rest.tgz) (1.7G, retrieved on 2007-12-19 by Thomas Zimmermann)
Eclipse Bugzilla export (in XML):
Bugs: [1-213000: eclipse-bugs--000001-213000.zip](http://pag.csail.mit.edu/msr_challenge2008/eclipse-bugs-000001-213000.zip) (3.2G, retrieved on 2007-12-19 by Thomas Zimmermann)


**6. PROMISE repo category (effort, requirements, model, defect, etc.)**

Others. It is a generic data set which can be categorized as bug analysis, change analysis, architecture and design, process analysis, team structure etc.

**7. General overview of the data**

![alt text](https://www.dropbox.com/s/8npl5jlgfuwuryr/Screenshot%202015-04-03%2015.48.11.png?dl=0 "Logo Title Text 1")
**8. Attribute info**
*Too big for me to check*

**9. Paper abstract (if appropriate)**

Prior research suggests that predicting defect-inducing changes,
i.e., Just-In-Time (JIT) defect prediction is a more practical
alternative to traditional defect prediction techniques, providing
immediate feedback while design decisions are still
fresh in the minds of developers. Unfortunately, similar to
traditional defect prediction models, JIT models require a
large amount of training data, which is not available when
projects are in initial development phases. To address this
flaw in traditional defect prediction, prior work has proposed
cross-project models, i.e., models learned from older
projects with su!cient history. However, cross-project models
have not yet been explored in the context of JIT prediction.
Therefore, in this study, we empirically evaluate the
performance of JIT cross-project models. Through a case
study on 11 open source projects, we find that in a JIT
cross-project context: (1) high performance within-project
models rarely perform well; (2) models trained on projects
that have similar correlations between predictor and dependent
variables often perform well; and (3) ensemble learning
techniques that leverage historical data from several other
projects (e.g., voting experts) often perform well. Our findings
empirically confirm that JIT cross-project models learned
using other projects are a viable solution for projects with
little historical data. However, JIT cross-project models perform
best when the data used to learn them is carefully selected.

**10. Is this dataset part of a larger series or collection?**
No

**Comment by vivekaxl** [comment]
https://www.dropbox.com/s/8npl5jlgfuwuryr/Screenshot%202015-04-03%2015.48.11.png?dl=0

**Comment by reesjones** [comment]
Added as [jit](http://openscience.us/repo/other/jit.html). Data not uploaded.

**Comment by reesjones** [comment]
Is this data the same as [msr11](https://terapromise.csc.ncsu.edu:8443/!/#repo/view/head/msr/msr11)? Most of the filenames are the same.

**Comment by reesjones** [comment]
Added as [jit](http://openscience.us/repo/other/jit.html).
