### ISSUE TITLE
Developers’ Code Context Models for Change Tasks

### ISSUE THREAD

**Issue by GeorgePanzerMathew** [opensciences/opensciences.github.io#175]
Thomas Fritz†
fritz@ifi.uzh.ch
David C. Shepherd*
david.shepherd@us.abb.com
Katja Kevic†
kevic@ifi.uzh.ch
Will Snipes*
will.snipes@us.abb.com
Christoph Bräunlich†
christoph.braeunlich@uzh.ch
†Department of Informatics *
Industrial Software Systems
University of Zurich ABB Corporate Research
Switzerland Raleigh NC USA

Dataset link Broken: https://github.com/abb-iss/study-artifacts-for-codecontext-models

Try emailing the authors

**Comment by Amoula1** [comment]
**Link To the paper: http://laser.inf.ethz.ch/2014/students/kevic.pdf
**Datasets:  open source projects.
