### ISSUE TITLE
Software Developers’ Perceptions of Productivity

### ISSUE THREAD

**Issue by GeorgePanzerMathew** [opensciences/opensciences.github.io#176]
Authors:
André N. Meyer, Thomas Fritz
(andre.meyer@uzh.ch, fritz@ifi.uzh.ch)
Gail C. Murphy
(murphy@cs.ubc.ca)
Thomas Zimmermann
(tzimmer@microsoft.com)

Dataset:
Data in graphical format. Its actually a survey result
src: https://onedrive.live.com/?cid=7672a64f9460fe35&id=7672A64F9460FE35%21140340

**Comment by reesjones** [comment]
I don't see a link to the actual paper?

**Comment by Amoula1** [comment]
Link to the paper: http://research.microsoft.com/pubs/228971/meyer-fse-2014.pdf

**Objectives: Amelioration of developers' productivity

**Main Contributions: 
1) Conducting two studies to investigate how developers perceive and assess their own productivity.
2) Proposition of ways to better support software developers in a retrospection and improvement of their productivity through the development of new tools and the sharing of best practices.

**Main Findings: ,we found that developers perceive their days as productive when they complete
many or big tasks without significant interruptions or context switches. 

Data:
The paper proposes qualitative studies in whic developers are asked many questions to assess their productivity.  The results of the survey is shown in the figure 
![image](https://cloud.githubusercontent.com/assets/10996072/6200832/19e0a4f0-b458-11e4-9d93-74039e13c95a.png)

==> There are no data which is explicitly published :/
