### ISSUE TITLE
Feedback Generation for Performance Problems in Introductory Programming Assignments

### ISSUE THREAD

**Issue by GeorgePanzerMathew** [opensciences/opensciences.github.io#178]
Authors:
Sumit Gulwani
Microsoft Research, USA
sumitg@microsoft.com
Ivan Radicek ˇ
TU Wien, Austria
radicek@forsyte.at
Florian Zuleger
TU Wien, Austria
zuleger@forsyte.at

src: http://delivery.acm.org/10.1145/2640000/2635912/p41-gulwani.pdf?ip=152.7.224.7&id=2635912&acc=ACTIVE%20SERVICE&key=6ABC8B4C00F6EE47%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&CFID=472254380&CFTOKEN=95848945&__acm__=1423860359_08bdac6872f6a9fa105e88c11af6a3dc

Data available as a table within the pdf on page(49)

**Comment by Amoula1** [comment]
**Link to the paper: 
http://sci-hub.org/downloads/3dd8/10.0000@arxiv.org@generic-FB29DFC77EDA.pdf

**Objective: Addressing the problem of generating feedback on performance aspects in introductory programming assignments.

**Main contribution: Proposition of a light-weight programming language extension that allows a teacher to define an algorithmic strategy by specifying certain key values that should occur during
the execution of an implementation.

** Experimental results: Our experimental results illustrate the effectiveness of both our specification language and our dynamic analysis. On one of our benchmarks consisting of 2316 functionally correct implementations to 3 programming problems, we identified 16 strategies that we were
able to describe using our specification language (in 95 minutes after inspecting 66, i.e., around 3%, implementations). 

**Data: Data. We used 3 preexisting problems from Pex4Fun (as mentioned in §1): (1) the Anagram problem, where students are asked to test if two strings could be permuted to becomeequal, (2) the IsSorted problem, where students are asked to test if the input array is sorted, and (3) the Caesar problem, where students are asked to apply Caesar cipher to the input string.

==> No data links are provided.
