### ISSUE TITLE
need a thank you page for the FEB hackathong

### ISSUE THREAD

**Issue by timm** [opensciences/opensciences.github.io#194]
https://mail.google.com/mail/u/0/?ui=2&ik=1a223c935c&view=att&th=14b845c8805d1aa7&attid=0.1&disp=safe&realattid=1493019788123832320-local0&zw

https://mail.google.com/mail/u/0/?ui=2&ik=1a223c935c&view=att&th=14b845c8805d1aa7&attid=0.2&disp=safe&realattid=1493019788123832320-local1&z

https://mail.google.com/mail/u/0/?ui=2&ik=1a223c935c&view=att&th=14b845c8805d1aa7&attid=0.3&disp=safe&realattid=1493019788123832320-local2&zww

**Comment by reesjones** [comment]
Added here: http://openscience.us/repo/contribute/february13hackathon.html
Also on the [contribute page](http://openscience.us/repo/contribute)
