### ISSUE TITLE
FUSE

### ISSUE THREAD

**Issue by rahlk** [opensciences/opensciences.github.io#198]
Compress with 7z and add [data](https://drive.google.com/folderview?id=0B6dzef3D5CTBfkFFbHJTcDRHYzNRZDd5d3FXSk1vVzJkbWtXS3FtV3dGbFUzcFZUX0FPcDQ&usp=drive_web#list) to svn

**Comment by reesjones** [comment]
Added as [FUSE](http://openscience.us/repo/spreadsheet/fuse.html).
