### ISSUE TITLE
Tracking down root causes of defects in simulink models

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#209]
Paper link: http://dl.acm.org/citation.cfm?id=2642943

**Comment by bigfatnoob** [comment]
Paper: [Tracking Down Root Causes of Defects in Simulink Models](http://dl.acm.org/citation.cfm?id=2642943)
They have an automatic code generator in this [link](http://www.dspace.com/en/ltd/home/products
/sw/pcgs/targetli.cfm). Don't think is useful
