### ISSUE TITLE
Resilient user interface level tests

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#219]
Paper link: http://dl.acm.org/citation.cfm?id=2642954

**Comment by bigfatnoob** [comment]
**Paper**:[Resilient User Interface Level Tests](http://dl.acm.org/citation.cfm?id=2642954)
**Authors**:Heidar Pirzadeh(heidar.pirzadeh@hybris.com), Sara Shanian(sara.shanian@ift.ulaval.ca)
