### ISSUE TITLE
Tracing software build processes to uncover license compliance inconsistencies

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#225]
Paper link: http://dl.acm.org/citation.cfm?id=2643013

**Comment by Amoula1** [comment]
Studying seven open source systems presented in the figure but there is No link to the data.
![image](https://cloud.githubusercontent.com/assets/10996072/6986088/fbd13792-da07-11e4-9315-7ffed75ac403.png)
