### ISSUE TITLE
Constructing adaptive configuration dialogs using crowd data

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#231]
Paper link: http://dl.acm.org/citation.cfm?id=2642960

**Comment by bigfatnoob** [comment]
**Paper**: [Constructing adaptive configuration dialogs using crowd data](http://dl.acm.org/citation.cfm?id=2642960)
**Authors**: Saeideh Hamidi, Periklis Andritsos, Sotirios Liaskos
**Email**: hamidi@yorku.ca, periklis.andritsos@unil.ch, liaskos@yorku.ca
**Bibliography**: @inproceedings{Hamidi:2014:CAC:2642937.2642960,
 author = {Hamidi, Saeideh and Andritsos, Periklis and Liaskos, Sotirios},
 title = {Constructing Adaptive Configuration Dialogs Using Crowd Data},
 booktitle = {Proceedings of the 29th ACM/IEEE International Conference on Automated Software Engineering},
 series = {ASE '14},
 year = {2014},
 isbn = {978-1-4503-3013-8},
 location = {Vasteras, Sweden},
 pages = {485--490},
 numpages = {6},
 url = {http://doi.acm.org/10.1145/2642937.2642960},
 doi = {10.1145/2642937.2642960},
 acmid = {2642960},
 publisher = {ACM},
 address = {New York, NY, USA},
 keywords = {association rules mining, crowdsourcing, facebook, markov decision processes, software customization},
} 
Dataset Used : Its the UCI repository [mushroom](https://archive.ics.uci.edu/ml/datasets/Mushroom).
