### ISSUE TITLE
Abstraction-aware verifying compiler for yet another MDD

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#239]
Paper link: http://dl.acm.org/citation.cfm?id=2642952

**Comment by bigfatnoob** [comment]
**Paper**: [Abstraction-aware verifying compiler for yet another MDD](http://dl.acm.org/citation.cfm?id=2642952)
**Author**: Naoyasu Ubayashi, Di Ai Peiyuan, Li Yu Ning Li, Shintaro Hosoai, Yasutaka Kamei
**Email**: ubayashi@acm.org, {aidi@posl.ait, lipeiyuan@posl.ait, liyuning@posl.ait, hosoai@qito, kamei@ait}.kyushu-u.ac.jp
