### ISSUE TITLE
Selection and presentation practices for code example summarization

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#244]
Link to data: http://dl.acm.org/citation.cfm?id=2635877

**Comment by bigfatnoob** [comment]
**Paper**: Selection and presentation practices for code example summarization
**Authors**: Annie T. T. Ying and Martin P. Robillard
**Email**: {annie.ying,martin}@cs.mcgill.ca

No data available as the paper primarily describes practices and they use actual sourcecode for them
