### ISSUE TITLE
Discovering refactoring opportunities in cascading style sheets

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#247]
Paper link: http://dl.acm.org/citation.cfm?id=2635879

**Comment by bigfatnoob** [comment]
**Title** : Discovering Refactoring Opportunities in Cascading Style Sheets
**Authors** : Davood Mazinanian, Nikolaos Tsantalis, Ali Mesbah
**Email** : {d_mazina, tsantalis}@cse.concordia.ca , amesbah@ece.ubc.ca
**Website** : http://users.encs.concordia.ca/~d_mazina/papers/FSE'14/
**Link To Dataset** : http://users.encs.concordia.ca/~d_mazina/papers/FSE'14/FSE'14-crawled.7z
**BibTex** : 
@inproceedings{Mazinanian:2014:DRO:2635868.2635879,
 author = {Mazinanian, Davood and Tsantalis, Nikolaos and Mesbah, Ali},
 title = {Discovering Refactoring Opportunities in Cascading Style Sheets},
 booktitle = {Proceedings of the 22Nd ACM SIGSOFT International Symposium on Foundations of Software Engineering},
 series = {FSE 2014},
 year = {2014},
 isbn = {978-1-4503-3056-5},
 location = {Hong Kong, China},
 pages = {496--506},
 numpages = {11},
 url = {http://doi.acm.org/10.1145/2635868.2635879},
 doi = {10.1145/2635868.2635879},
 acmid = {2635879},
 publisher = {ACM},
 address = {New York, NY, USA},
 keywords = {Cascading style sheets, duplication, refactoring},
} 
**Overview** : Contains  CSS code and this [link](http://users.encs.concordia.ca/~d_mazina/papers/FSE'14/FSE'14.csv) which indicates different measures for CSS datasets.
**Promise Repo Category** : Code Analysis

**Comment by reesjones** [comment]
Added as [refactorcss](http://openscience.us/repo/code-analysis/refactorcss.html), data being uploaded.

**Comment by reesjones** [comment]
Data uploaded, authors emailed.
