### ISSUE TITLE
An empirical study on program comprehension with reactive programming

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#253]
Paper link: http://dl.acm.org/citation.cfm?id=2635895

**Comment by WeiFoo** [comment]
This paper is more like programming behavior analysis. And the experiment is based on programming tasks. They do have some data sets like http://www.guidosalvaneschi.com/wp/software/empirical-study-on-rp/, but for the time being, I don't believe this should be included by our promise repo.
I would close it
