### ISSUE TITLE
Detecting energy bugs and hotspots in mobile apps

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#255]
Paper link: http://dl.acm.org/citation.cfm?id=2635871

**Comment by bigfatnoob** [comment]
**Title** : Detecting Energy Bugs and Hotspots in Mobile Apps
**Authors** : Abhijeet Banerjee1 Lee Kee Chong1 Sudipta Chattopadhyay2 Abhik Roychoudhury1
