### ISSUE TITLE
Improving oracle quality by detecting brittle assertions and unused inputs in tests

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#258]
Paper link: http://dl.acm.org/citation.cfm?id=2635917

**Comment by vivekaxl** [comment]
The goal of the technique is to improve oracle quality by
detecting brittle assertions and unused inputs. To suitably
evaluate the technique with respect to this goal, we selected
the test suites of 20 applications as our subjects. Table 1
describes the applications. In the table, the first column,
Subject shows the name and version of each application, if
available. The first eight applications (CommissionEmployee
through Sudoku) are taken from the Proteja Test Suite Executor
and Coverage Monitor repository.4 The remaining
subjects were obtained from various repositories including:
(1) the Software-artifact Infrastructure Repository (SIR),5
which provides a variety of open-source projects for empirical
software engineering, (2) SourceForge,6
a popular repository
for open-source projects, and (3) Apache Commons,7
a collection
of reusable components. The second column, LoC,
shows the number of non-blank, non-comment, lines of code
that comprise the application and the third column, # Tests
shows the number of tests in each application’s test suite.

* The data used by the authors are test cases from various open source software. I am not sure if we really want to store code bases in promise *

**Comment by vivekaxl** [comment]
https://bitbucket.org/udse/oraclepolish-wala/downloads
https://bitbucket.org/udse/oraclepolish-jpf/downloads
