### ISSUE TITLE
Meta-Model validation and verification with MetaBest

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#271]
Paper link: http://dl.acm.org/citation.cfm?id=2648617

**Comment by bigfatnoob** [comment]
**Title** : Meta-Model Validation and Verification with MetaBest
**Authors** : Jesús J. López-Fernández, Esther Guerra, Juan de Lara
**Email** : {Jesusj.Lopez, Esther.Guerra, Juan.deLara}@uam.es
