### ISSUE TITLE
DupFinder: integrated tool support for duplicate bug report detection

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#285]
Paper link: http://dl.acm.org/citation.cfm?id=2648627

**Comment by bigfatnoob** [comment]
**Paper**:[DupFinder: integrated tool support for duplicate bug report detection](http://dl.acm.org/citation.cfm?id=2648627)
**Authors**:Ferdian Thung, Pavneet Singh Kochhar, and David Lo
**Email**:{ferdiant.2013,kochharps.2012,davidlo}@smu.edu.sg

Dataset: Bugzilla(http://www.bugzilla.org/) report
