### ISSUE TITLE
Embrace your issues: compassing the software engineering landscape using bug reports

### ISSUE THREAD

**Issue by reesjones** [opensciences/opensciences.github.io#286]
Paper link: http://dl.acm.org/citation.cfm?id=2653469

**Comment by bigfatnoob** [comment]
**Paper**: Embrace your issues: compassing the software engineering landscape using bug reports(http://dl.acm.org/citation.cfm?id=2653469)
**Author**: Markus Borg
**Email**: markus.borg@cs.lth.se
**Dataset**: Issue reports from [lucene](http://lucene.apache.org) are used to train the data

**Comment by reesjones** [comment]
Is there a reason that this issue isn't closed? If not then we should close it. @bigfatnoob
