### ISSUE TITLE
Utilizing feature location techniques for feature addition and feature enhancement

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#289]
Paper link: http://dl.acm.org/citation.cfm?id=2653466

**Comment by bigfatnoob** [comment]
**Paper**:[Utilizing feature location techniques for feature addition and feature enhancement](http://dl.acm.org/citation.cfm?id=2653466)
**Author**:Joseph Burke
**Email**:joseph.burke@lero.ie 
**Dataset**: No dataset available
