### ISSUE TITLE
Why so complicated? Simple term filtering and weighting for location-based bug report assignment recommendation

### ISSUE THREAD

**Issue by reesjones** [opensciences/opensciences.github.io#309]
Paper link: http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6623997

**Comment by bigfatnoob** [comment]
**Title** : Why So Complicated? Simple Term Filtering and Weighting fo rLocation-Based Bug Report Assignment Recommendation
**Authors** : Ramin Shokripour, John Anvik, Zarinah M. Kasirun, Sima Zamani
**Email** : shokripour@siswa.um.edu.my , zarinahmk@um.edu.my , sima.zamani@siswa.um.edu.my , janvik@cwu.edu

**Data** : Bug Reports from Eclipse and Mozilla projects on bugzilla
