### ISSUE TITLE
 Bug report assignee recommendation using activity profiles

### ISSUE THREAD

**Issue by reesjones** [opensciences/opensciences.github.io#315]
Paper link: http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6623999

**Comment by djidjimapa2** [comment]
the authors has this dataset : the bug report quality, triaging process, and bug tracking activities.
but there is no link for the dataset .

**Comment by djidjimapa2** [comment]
the authors describe the tool : GuideArch , no dataset available
