### ISSUE TITLE
Learning revised models for planning in adaptive systems

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#318]
http://dl.acm.org/citation.cfm?id=2486797

**Comment by bigfatnoob** [comment]
No data found. Link to a software model from another paper used as data
(N. D’Ippolito, V. Braberman, N. Piterman, and S. Uchitel. Synthesis of
live behaviour models. In Proceedings of the eighteenth ACM SIGSOFT
international symposium on Foundations of software engineering, pages
77–86. ACM, 2010.)
