### ISSUE TITLE
 Who does what during a code review? Datasets of OSS peer review repositories

### ISSUE THREAD

**Issue by reesjones** [opensciences/opensciences.github.io#342]
Paper linkK: http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6624003

**Comment by WeiFoo** [comment]
http://sdlab.naist.jp/reviewmining/

**Comment by WeiFoo** [comment]
Title : Who does what during a code review? Datasets of OSS peer review repositories
Authors :Kazuki Hamasaki, Raula Gaikovina Kula, Norihiro Yoshida, Ana Erika Camargo Cruz, Kenji Fujiwara and Hajimu Iida
Email :{kazuki-h, raula-k, yoshida, camargo, kenji-f}@is.naist.jp, iida@itc.naist.jp
Website : http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6624003
Link To Dataset : http://sdlab.naist.jp/reviewmining/

 @INPROCEEDINGS{6624003, 
author={Hamasaki, K. and Kula, R.G. and Yoshida, N. and Cruz, A.E.C. and Fujiwara, K. and Iida, H.}, 
booktitle={Mining Software Repositories (MSR), 2013 10th IEEE Working Conference on}, 
title={Who does what during a code review? Datasets of OSS peer review repositories}, 
year={2013}, 
month={May}, 
pages={49-52}, 
keywords={data mining;public domain software;software quality;Android project;OSS peer review repositories;code review;code source repositories;data mining;extraction methodology;integrated peer review system;software quality assurance activity;Androids;Complexity theory;Data mining;Humanoid robots;Radiation detectors;Social network services;Software;Open Source Software;Peer Review Repository Mining;Quality Assurance}, 
doi={10.1109/MSR.2013.6624003}, 
ISSN={2160-1852},}
Abstract:We present four datasets that are focused on the general roles of OSS peer review members. With data mined from both an integrated peer review system and code source repositories, our rich datasets comprise of peer review data that was automatically recorded. Using the Android project as a case study, we describe our extraction methodology, the datasets and their application used for three separate studies. Our datasets are available online at http://sdlab.naist.jp/reviewmining/

Promise Repo Category : Code Analysis
