### ISSUE TITLE
 Search-based duplicate defect detection: An industrial experience

### ISSUE THREAD

**Issue by reesjones** [opensciences/opensciences.github.io#369]
Paper link: http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6624025

**Comment by bigfatnoob** [comment]
Title : Search-based duplicate defect detection: An industrial experience
Authors : Mehdi Amoui, Nilam Kaushik, Abraham Al-Dabbagh, Ladan Tahvildari
Email : {mamouika, nkaushik, ataldabb, ltahvild}@uwaterloo.ca

Dataset from bugzilla
