### ISSUE TITLE
 Revisiting software development effort estimation based on early phase development activities

### ISSUE THREAD

**Issue by reesjones** [opensciences/opensciences.github.io#387]
Paper link: http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6624059

**Comment by bigfatnoob** [comment]
**Title** : Revisiting Software Development Effort Estimation Based on Early Phase Development Activities
**Authors** : Masateru Tsunoda, Koji Toda, Kyohei Fushida
**Email** : tsunoda@ieee.org, toda@fit.ac.jp, fushidak@nttdata.co.jp

Data exists in [promise](http://openscience.us/repo/effort/function-points/china.html)

**Comment by bigfatnoob** [comment]
#449
