### ISSUE TITLE
Strategies for avoiding text fixture smells during software evolution

### ISSUE THREAD

**Issue by reesjones** [opensciences/opensciences.github.io#393]
Paper link: http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6624053

**Comment by bigfatnoob** [comment]
**Title** : Strategies for Avoiding Text Fixture Smells during Software Evolution
**Authors** : Michaela Greiler, Andy Zaidman and Arie van Deursen
**Email** : {m.s.greiler,a.e.zaidman,arie.vandeursen}@tudelft.nl
