### ISSUE TITLE
Project roles in the Apache Software Foundation: A dataset

### ISSUE THREAD

**Issue by reesjones** [opensciences/opensciences.github.io#404]
http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6624042

**Comment by bigfatnoob** [comment]
**Title** : Project roles in the Apache Software Foundation: A dataset
**Authors** : Megan Squire
**Email** : msquire@elon.edu
**BibTex** : @inproceedings{Squire:2013:PRA:2487085.2487142,
 author = {Squire, Megan},
 title = {Project Roles in the Apache Software Foundation: A Dataset},
 booktitle = {Proceedings of the 10th Working Conference on Mining Software Repositories},
 series = {MSR '13},
 year = {2013},
 isbn = {978-1-4673-2936-1},
 location = {San Francisco, CA, USA},
 pages = {301--304},
 numpages = {4},
 url = {http://dl.acm.org/citation.cfm?id=2487085.2487142},
 acmid = {2487142},
 publisher = {IEEE Press},
 address = {Piscataway, NJ, USA},
}

**Link to Dataset** : [link](https://code.google.com/p/flossmole/downloads/detail?name=apachePeople2013-Jan.zip)
**Promise Repo Category** : Other(Project Roles)

**Overview** : Contains 3 tables in sql format

Table 1 (apache_datasources): List of Apache Data sources
Attributes (Name, Type): 
  `datasource_id` Integer
  `item_description` Character
  `date_posted` Date
  `date_collected` Date
  `method` Character
  `item_url` Character
  `last_updated` Date

Table 2(apache_people_projects) : List of people committing various projects
Attributes (Name, Type):
  `svn_id` Character
  `real_name` Character
  `web_site` Character
  `datasource_id` Integer
  `project_name` Character
  `role_on_project` Character
  `details` Character
  `email` Character
  `organization` Character
  `last_updated` Date

Table 3(apache_unlisted_cla): List of people with signed CLAs but are not committers
Attributes (Name, Type):
  `real_name` Character
  `datasource_id` Integer
  `last_updated` Date

**Abstract**: This paper outlines the steps in the creation and maintenance of a new dataset listing leaders of the various projects of the Apache Software Foundation (ASF). Included in this dataset are different levels of committers to the various ASF project code bases, as well as regular and emeritus members of the ASF, and directors and officers of the ASF. The dataset has been donated to the FLOSSmole project under an open source license, and is available for download (https://code.google.com/p/flossmole/downloads/detail?name=apachePeople2013-Jan.zip), or for direct querying via a database client

**Comment by reesjones** [comment]
Added as [apachesquire](http://openscience.us/repo/other/apachesquire.html).
