### ISSUE TITLE
Automatic patch generation learned from human-written patches

### ISSUE THREAD

**Issue by CarterPape** [opensciences/opensciences.github.io#448]
http://dl.acm.org/citation.cfm?id=2486893

**Comment by obaysal** [comment]
The authors investigated 62,656 human-written patches were collected from Eclipse JDT4. Their new patch generation approach, PAR, was evaluated on 119 real bugs from open source projects. 

All materials used in this paper and detailed patch generation results are available: https://sites.google.com/site/autofixhkust/
