### ISSUE TITLE
Possible Effort Datasets

### ISSUE THREAD

**Issue by bigfatnoob** [opensciences/opensciences.github.io#449]
Paper link: http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6624059

Refer to page 435 , they refer 2 datasets in **section E**, ERA and SEC both by companies from Japan. Was unable to find them on the internet. You could mail the authors asking more information

**Comment by bigfatnoob** [comment]
#387

**Comment by timm** [comment]
emails sent to authors looking for data (may1). lets see what happens.

**Comment by timm** [comment]
reply: Hi Tim,

The ERA and SEC data were not our data. We used CSBSG data which was under NDI between my former employer and SPI China, the organization who collected the data. Sorry!
