### ISSUE TITLE
Dublicated categories (Search-Based SE and Search-based SE)

### ISSUE THREAD

**Issue by obaysal** [opensciences/opensciences.github.io#450]

**Comment by reesjones** [comment]
@obaysal How did you find this error? If it was with the search bar, then it might be because it's a Google custom site search and the search engine hasn't updated the pages yet.

**Comment by obaysal** [comment]
See the screenshot of what I mean here. 
![screenshot_categories](https://cloud.githubusercontent.com/assets/6673687/7480783/110553a6-f339-11e4-8006-07ef1ef4c21c.png)

**Comment by reesjones** [comment]
Ah, I see. When I was reordering them I forgot to take that out. It's now removed.
