### ISSUE TITLE
respond to these folks by may 5

### ISSUE THREAD

**Issue by timm** [opensciences/opensciences.github.io#505]
email from them apr 28 and may 1.

taken care off?

Hi,
Yes, please change the download for Haggis to these datasets. 

Let us know if we can be of any further help with the Java GitHub Corpus.

Thanks,
Miltos

On Fri, May 1, 2015 at 11:37 AM, Open science Content <openscience.content@gmail.com> wrote:
Hello,

With your permission, we will change the download for our haggis dataset to link to MSR13 and the Java GitHub Corpus. We have added the "Mining source code repositories at massive scale using language modeling" paper to our queue of datasets to add; we'll send another email once it's been added.

Thank you for your contributions!

**Comment by reesjones** [comment]
I've almost finished uploading this data and will email back tonight.
