### ISSUE TITLE
MDE IN INDUSTRY

### ISSUE THREAD

**Issue by dapryor** [opensciences/opensciences.github.io#511]
suggest-name: 	MDEinIndustry

category: 	Social Analysis

link-to-dataset: 	http://dl.acm.org/citation.cfm?id=1426373

data-source: 	Where Is the Proof? - A Review of Experiences from Applying MDE in Industry

paper-link: 	http://dl.acm.org/citation.cfm?id=1426373

authors: 	Parastoo Mohagheghi : Parastoo.Mohagheghi@sintef.no
Vegard Dehlen : Vegard.Dehlen@sintef.no

bibtex: 	This paper is a review of 25 other paper published between the years 2000 to 2007. This paper provides a good reference for future work.
overview: 	The data collected for this study is basically 25 research papers presented between years 2000 to 2007 at various conferences and journals. All these paper deals with Model Driven Engineering and its applications in industry. The aim of the paper was to review all these papers and to determine what problems are faced by various industries in employing MDE in their process.
attributes: 	

part-of-a-larger-collection: 	Yes
link-to-larger-collection:

**Comment by reesjones** [comment]
No data, closing
