### ISSUE TITLE
Randomized Algorithm Publications in 2009

### ISSUE THREAD

**Issue by dapryor** [opensciences/opensciences.github.io#513]
suggest-name: 	Randomized Algorithm Publications in 2009

category: 	Software Engineering

link-to-dataset: 

data-source: 	A Practical Guide for Using Statistical Tests to Assess Randomized Algorithms in Software Engineering

paper-link: 	http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6032439&tag=1

authors: 	Andrea Arcui (arcuri@simula.no), Lionel Briand (briand@simula.no)

bibtex: 
@INPROCEEDINGS{6032439, 
author={Arcuri, A. and Briand, L.}, 
booktitle={Software Engineering (ICSE), 2011 33rd International Conference on}, 
title={A practical guide for using statistical tests to assess randomized algorithms in software engineering}, 
year={2011}, 
pages={1-10}, 
keywords={software engineering;statistical analysis;practical guide;randomized algorithms;snapshot representation;software engineering;statistical tests;Algorithm design and analysis;Context;Search problems;Software algorithms;Software engineering;Statistical analysis;Testing;bonferroni adjustment;confidence interval;effect size;non-parametric test;parametric test;statistical difference;survey;systematic review}, 
doi={10.1145/1985793.1985795}, 
ISSN={0270-5257}, 
month={May},}

overview: 	The dataset consists of 16 publications on randomized algorithms found through a systematic review of IEEE Transactions of Software Engineering (TSE) and IEEE International Conference on Software Engineering (ICSE).

attributes:part-of-a-larger-collection: 	Yes

link-to-larger-collection:

**Comment by bigfatnoob** [comment]
No Data . Just techniques on how to use statistical tests on randomized algos
