### ISSUE TITLE
iStar 1: Smaller models

### ISSUE THREAD

**Issue by bigfatnoob** [opensciences/opensciences.github.io#532]
**Name** : Softgoals(.ood files)
**Category** : Requirements Engineering
**Link To Dataset** : https://github.com/ai-se/softgoals/tree/master/GMRepo/CMA12
 Use all the files with .ood extension in this directory.
**Link to Material** : http://link.springer.com/article/10.1007%2Fs00766-014-0209-8
Additional papers for reference can be accessed [here ](https://github.com/ai-se/softgoals/tree/master/pdf)
**BibTex** : 
```
@article{
year={2014},
issn={0947-3602},
journal={Requirements Engineering},
doi={10.1007/s00766-014-0209-8},
title={Interactive goal model analysis for early requirements engineering},
url={http://dx.doi.org/10.1007/s00766-014-0209-8},
publisher={Springer London},
keywords={Goal-oriented requirements engineering; Goal modeling; Modeling; Model analysis; Model iteration; Interactive modeling; Satisfaction analysis},
author={Horkoff, Jennifer and Yu, Eric},
pages={1-33},
language={English}
}
```
**Overview of Data** : 
.ood files are essentially .xml files which can be parsed to construct the graph by identifying its nodes and edges. A parser to parse these files can be obtained [here](https://github.com/ai-se/softgoals/blob/master/src/parser/OMETree.py)

**Comment by dapryor** [comment]
Added to promise
