### ISSUE TITLE
iStar 2: Larger models

### ISSUE THREAD

**Issue by bigfatnoob** [opensciences/opensciences.github.io#533]
**Name** : Softgoals(.vsd files)
**Category** : Requirements Engineering
**Link To Dataset** : https://github.com/ai-se/softgoals/tree/master/GMRepo/Counseling%20Service
 Use all the files with .vsd extension in this directory.
**Link to Material** : http://link.springer.com/article/10.1007%2Fs00766-014-0209-8
Additional papers for reference can be accessed [here ](https://github.com/ai-se/softgoals/tree/master/pdf)
**BibTex** : 
```
@article{
year={2014},
issn={0947-3602},
journal={Requirements Engineering},
doi={10.1007/s00766-014-0209-8},
title={Interactive goal model analysis for early requirements engineering},
url={http://dx.doi.org/10.1007/s00766-014-0209-8},
publisher={Springer London},
keywords={Goal-oriented requirements engineering; Goal modeling; Modeling; Model analysis; Model iteration; Interactive modeling; Satisfaction analysis},
author={Horkoff, Jennifer and Yu, Eric},
pages={1-33},
language={English}
}
```
**Overview of Data** : 
.vsd files are essentially .xml files which cannot be parsed as we cannot estimate a generic pattern amongst the files to construct a parser. A domain specific language in python is used to draw these models. The template for the DSL can be accessed [here](https://github.com/ai-se/softgoals/blob/master/src/pystar/template.py) and a sample model can be accessed [here](https://github.com/ai-se/softgoals/blob/master/src/pystar/models/bCMS_SR_Witness.py).

**Comment by dapryor** [comment]
Added to promise
