### ISSUE TITLE
 DexterJS: robust testing platform for DOM-based XSS vulnerabilities

### ISSUE THREAD

**Issue by azhe825** [opensciences/opensciences.github.io#543]
http://dl.acm.org/citation.cfm?id=2803191&CFID=556825173&CFTOKEN=35211747

**Comment by hsneedham** [comment]
There are no direct comparisons or list of variables between the tools they compare to, for example FLAX, Jalangi and DOMinatorPRO. In addition they do not have any comparisons between the different tools and the vulnerabilities they found
