### ISSUE TITLE
Commit guru: analytics and risk prediction of software commits

### ISSUE THREAD

**Issue by azhe825** [opensciences/opensciences.github.io#548]
http://dl.acm.org/citation.cfm?id=2803183&CFID=556825173&CFTOKEN=35211747

**Comment by hsneedham** [comment]
No raw data is available

**Comment by hsneedham** [comment]
There is no raw data that indicates how they identified risky software commits and the relationship to predictions against the projects they tested it against. Neither do they list the projects they tested their tool with
