### ISSUE TITLE
Comprehensive service matching with MatchBox

### ISSUE THREAD

**Issue by azhe825** [opensciences/opensciences.github.io#550]
http://dl.acm.org/citation.cfm?id=2803181&CFID=556825173&CFTOKEN=35211747

**Comment by hsneedham** [comment]
They contrast their tool to other tools but provide no data set

**Comment by hsneedham** [comment]
They contrast their tool to other tools but do not provide a list of relevant tools they contrasted themselves to nor do they provide and data set(s) or direct comparisons to current available tools
