### ISSUE TITLE
Turning programs against each other: high coverage fuzz-testing using binary-code mutation and dynamic slicing

### ISSUE THREAD

**Issue by amritbhanu** [opensciences/opensciences.github.io#551]
http://dl.acm.org/citation.cfm?id=2786844&CFID=542094983&CFTOKEN=45327393

**Comment by hsneedham** [comment]
This paper is about a tool they developed for generating random data for software and security testing. and compared it against two other tools

**Comment by hsneedham** [comment]
Reopened to get rid of Maybe has data because it has data

**Comment by hsneedham** [comment]
Added new label to indicate that is has a dataset
