### ISSUE TITLE
Rule-based extraction of goal-use case models from text

### ISSUE THREAD

**Issue by Ginfung** [opensciences/opensciences.github.io#571]
http://dl.acm.org/citation.cfm?id=2786876&CFID=725626965&CFTOKEN=17951443

**Comment by alisher13** [comment]
The authors evaluate the effectiveness of GUEST in extracting goal-use case models from requirements documents. They provide a link (http://www.ict.swin.edu.au/personal/huannguyen/guitar.html) to the dataset they used. The link works and leads to the dataset files containing web page.
