### ISSUE TITLE
Efficient and reasonable object-oriented concurrency

### ISSUE THREAD

**Issue by Ginfung** [opensciences/opensciences.github.io#583]
http://dl.acm.org/citation.cfm?id=2786822&CFID=725626965&CFTOKEN=17951443

**Comment by junaidmaqbutt** [comment]
The paper suggested an algorithm and used parallel and concurrent benchmark to evaluate. There was no actual data-set used. It was a tool to define the time usage using different benchmark settings. They do refer to the tool (The one for benchmark)  named Computer Language Benchmarks Game.
