### ISSUE TITLE
FlexJava: language support for safe and modular approximate programming

### ISSUE THREAD

**Issue by Ginfung** [opensciences/opensciences.github.io#584]
http://dl.acm.org/citation.cfm?id=2786807&CFID=725626965&CFTOKEN=17951443

**Comment by junaidmaqbutt** [comment]
The paper basically uses a benchmark statistics to evaluate their idea. They did gave a link to their results and also did define a complete process if someone wants to get the results back or to take the study to the next level. Here is the link for the benchmarks 
https://bitbucket.org/act-lab/profile/repositories

But apart from that there is no actual data-set used or defined within the paper.
