### ISSUE TITLE
Efficient dependency detection for safe Java test acceleration

### ISSUE THREAD

**Issue by Ginfung** [opensciences/opensciences.github.io#586]
http://dl.acm.org/citation.cfm?id=2786823&CFID=725626965&CFTOKEN=17951443

**Comment by hk027** [comment]
This paper uses data of  popular java projects from open repository site, GitHub. The paper doesn't provide any link to dataset. . There  is not dataset available in this paper. A list of 921 Java projects are used in this paper. A email should be sent to the authors.
