### ISSUE TITLE
The making of cloud applications: an empirical study on software development for the cloud

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#588]
http://dl.acm.org/ft_gateway.cfm?id=2786826&ftid=1615613&dwn=1&CFID=725641379&CFTOKEN=87982003

**Comment by hk027** [comment]
This paper uses interviews to collect data. This paper doesn't provide dataset, it provide only the quantitative Survey questions and the qualitative interview  study. Raw data are not available.  this is the link to surveys : http://www.ifi.uzh.ch/seal/people/cito/cloud-developer-study.html
