### ISSUE TITLE
 What change history tells us about thread synchronization

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#591]
http://dl.acm.org/ft_gateway.cfm?id=2786815&ftid=1615552&dwn=1&CFID=725641379&CFTOKEN=87982003

**Comment by junaidmaqbutt** [comment]
The paper used 4 datasets
1- SVN for Apache (hosted at official Apache Site )
2- SVN for MPlayer (hosted at mplayerhq.hu)
3- Mercurial for Mozilla (hosted at official Mozilla site) 
4- Bazaar for MySQL (hosted at official MySQL Site)

In total the data-set used had 250,000 revisions all together.
