### ISSUE TITLE
Effective and precise dynamic detection of hidden races for Java programs

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#593]
http://dl.acm.org/ft_gateway.cfm?id=2786839&ftid=1615535&dwn=1&CFID=725641379&CFTOKEN=87982003

**Comment by junaidmaqbutt** [comment]
The paper used the open source virtual machine technology to do the testing which contains numerous benchmark tools within it (http://www.jikesrvm.org) No actual data set which could be helpful to the community was used.
