### ISSUE TITLE
Heterogeneous cross-company defect prediction by unified metric representation and CCA-based transfer learning

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#597]
http://dl.acm.org/ft_gateway.cfm?id=2786813&ftid=1615537&dwn=1&CFID=725641379&CFTOKEN=87982003

**Comment by Iman-Es** [comment]
In their experiment they have used 14 publicly available datasets from four different companies: NASA, SOFTLAB, ReLink and AEEEM as the test data, but there is no link to the actual datasets in one place as they have been collected from different places:
Datasets from SOFTLAB and NASA are obtained from PROMISE repository (http://promisedata.org/repository, 2007)
AEEEM dataset is collected by D’Ambros et al [24]
ReLink dataset is collected by Wu et al. [23]
