### ISSUE TITLE
Heterogeneous defect prediction

### ISSUE THREAD

**Issue by WeiFoo** [opensciences/opensciences.github.io#598]
http://dl.acm.org/ft_gateway.cfm?id=2786814&ftid=1615615&dwn=1&CFID=725641379&CFTOKEN=87982003

**Comment by wafahasanain** [comment]
This paper used five groups with 28 defect datasets: AEEEM, ReLink, MORPH, NASA, and SOFTLAB.

**Comment by WeiFoo** [comment]
Do we already have AEEEM,ReLink in PROMISE?

**Comment by wafahasanain** [comment]
The authors said that they used data sets from promise. but when i checked it now they are not there. would u like me to add them?   


     On Friday, October 30, 2015 11:33 AM, Wei Fu <notifications@github.com> wrote:
   

 Do we already have AEEEM,ReLink in PROMISE?—

**Comment by WeiFoo** [comment]
I remember we don’t have Relink and AEEEM data sets. The other three we have.
Yes, thanks!

**Comment by wafahasanain** [comment]
I have submitted a donation forum for AEEEM dataset
