### ISSUE TITLE
Questions developers ask while diagnosing potential security vulnerabilities with static analysis

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#624]
http://dl.acm.org/citation.cfm?id=2786812&CFID=550839757&CFTOKEN=78411605

**Comment by sandyboon** [comment]
The paper conducted a study about the questions that developers ask while using static analysis tools to find security bugs.
The tool used is called "Find Security Bugs" (abbreviated as FSB).
