### ISSUE TITLE
On the use of delta debugging to reduce recordings and facilitate debugging of web applications

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#631]
http://dl.acm.org/citation.cfm?id=2786846&CFID=550839757&CFTOKEN=78411605

**Comment by alisher13** [comment]
They authors obtain data by survey. To do it they recruited 20 participants from the population of graduate and undergraduate students enrolled in the Department of Computer Science and Engineering at the University of Nebraska-Lincoln.
