### ISSUE TITLE
JITProf: pinpointing JIT-unfriendly JavaScript code

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#633]
http://dl.acm.org/citation.cfm?id=2786831&CFID=550839757&CFTOKEN=78411605

**Comment by alisher13** [comment]
The authors obtain performance data by performing multiple actions to (1) Open a fresh browser instance and run the original benchmark. (2) Open a fresh browser instance and run the modified benchmark. They provide the performance data in Table 5.
