### ISSUE TITLE
Interactive code review for systematic changes

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#646]
http://dl.acm.org/citation.cfm?id=2818771&CFID=550839757&CFTOKEN=78411605

**Comment by Iman-Es** [comment]
Their example is based on a diff patch at revision 13516 of SWT which is an open source widget toolkit with 400K lines of source code over 1000 files, but actual data set is not provided
Their test suite includes patches from Park et al.’s data set [21]
