### ISSUE TITLE
When and why your code starts to smell bad

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#676]
http://dl.acm.org/citation.cfm?id=2818805&CFID=550839757&CFTOKEN=78411605

**Comment by timm** [comment]
emailed authors, waiting response

![image](https://cloud.githubusercontent.com/assets/29195/10850006/d0061fe6-7ef9-11e5-8af8-e89e327c8dc4.png)

**Comment by timm** [comment]
data received from authors
