### ISSUE TITLE
The impact of mislabelling on the performance and interpretation of defect prediction models

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#718]
http://dl.acm.org/citation.cfm?id=2818852&CFID=550839757&CFTOKEN=78411605

**Comment by timm** [comment]
authors contacted. waiting response

![image](https://cloud.githubusercontent.com/assets/29195/10849340/b8a84494-7ef6-11e5-93d7-751bd0c4aa7b.png)

**Comment by timm** [comment]
authors replied. they used the same data as
http://openscience.us/repo/other/bugclassify.html
