### ISSUE TITLE
Chunk1 for FSE'14 

### ISSUE THREAD

**Issue by timm** [opensciences/opensciences.github.io#76]
# Source 

http://dl.acm.org/citation.cfm?id=2635876#prox

# SESSION: Keynote
Omlet: a revolution against big-brother social networks (invited talk)
Monica S. Lam
Pages: 1-1
doi>10.1145/2635868.2684426
Full text: PDFPDF

With the wide-spread adoption of proprietary social networks like Facebook and mobile chat platforms like Wechat, we may be heading to a future where all our communication are monetized and our online transactions are mediated by monopolistic big-data ... expand

# SESSION: Award Talks

## From software engineering to software systems (invited talk)

Alexander L. Wolf
Pages: 2-2
doi>10.1145/2635868.2684427
Full text: PDFPDF

I began my career in software engineering research and now find myself working more in software systems research. Is there a difference? In this talk I reflect on this question by recalling the stream of ideas, students, and colleagues that have shaped ... expand

## Ten years with evidence-based software engineering. What is it? Has it had any impact? What's next?

Magne Jørgensen
Pages: 3-3
doi>10.1145/2635868.2684428
Full text: PDFPDF

An evidence-based software engineer is one who is able to: 1) Formulate a question, related to a decision or judgment, so that it can be answered by the use of evidence, 2) Collect, critically evaluate and summarise relevant evidence from research, ... expand

# SESSION: Perspectives from Industry

## Experiences developing tools for developers (invited talk)

John Penix
Pages: 4-4
doi>10.1145/2635868.2684429
Full text: PDFPDF

Software Engineers are horrible customers for software tools. If they don't like your tools, they will just write their own. If your tool wastes a few minutes of a developer's day, good luck getting them to ever try your tool again. And if, ... expand

## Are you getting traction? tales from the tech transfer trenches (invited talk)

Satish Chandra
Pages: 5-5
doi>10.1145/2635868.2684430
Full text: PDFPDF

So you have developed a new software productivity tool, written an FSE or an ICSE paper about it, and are justifiably proud of your work. If you work for a company, your (curmudgeonly) manager now wants to see its “impact” on the business. ... expand

## Data hard with a vengeance (invited talk)

Thomas Zimmermann
Pages: 6-6
doi>10.1145/2635868.2684431
Full text: PDFPDF

Action flicks and the analysis of software data in industry have more in common than you think. Both action heroes and development teams are on tight deadlines to save the day. Getting wrong information can lead to disastrous outcomes. In this talk, ... expand

## SESSION: Helping and Understanding Developers

Developers' code context models for change tasks
Thomas Fritz, David C. Shepherd, Katja Kevic, Will Snipes, Christoph Bräunlich
Pages: 7-18
doi>10.1145/2635868.2635905
Full text: PDFPDF

To complete a change task, software developers spend a substantial amount of time navigating code to understand the relevant parts. During this investigation phase, they implicitly build context models of the elements and relations that are relevant ... expand

## Software developers' perceptions of productivity

André N. Meyer, Thomas Fritz, Gail C. Murphy, Thomas Zimmermann
Pages: 19-29
doi>10.1145/2635868.2635892
Full text: PDFPDF

The better the software development community becomes at creating software, the more software the world seems to demand. Although there is a large body of research about measuring and investigating productivity from an organizational point of view, ... expand

## Enablers, inhibitors, and perceptions of testing in novice software teams

Raphael Pham, Stephan Kiesling, Olga Liskin, Leif Singer, Kurt Schneider
Pages: 30-40
doi>10.1145/2635868.2635925
Full text: PDFPDF

There are many different approaches to testing software, with different benefits for software quality and the development process. Yet, it is not well understood what developers struggle with when getting started with testing - and why some do not test ... expand

## Feedback generation for performance problems in introductory programming assignments

Sumit Gulwani, Ivan Radiček, Florian Zuleger
Pages: 41-51
doi>10.1145/2635868.2635912
Full text: PDFPDF

Providing feedback on programming assignments manually is a tedious, error prone, and time-consuming task. In this paper, we motivate and address the problem of generating feedback on performance aspects in introductory programming assignments. We studied ... expand
SESSION: Debugging and Refactoring

## Test case purification for improving fault localization

Jifeng Xuan, Martin Monperrus
Pages: 52-63
doi>10.1145/2635868.2635906
Full text: PDFPDF

Finding and fixing bugs are time-consuming activities in software development. Spectrum-based fault localization aims to identify the faulty position in source code based on the execution trace of test cases. Failing test cases and their assertions ... expand

## Automatically generated patches as debugging aids: a human study

Yida Tao, Jindae Kim, Sunghun Kim, Chang Xu
Pages: 64-74
doi>10.1145/2635868.2635873
Full text: PDFPDF

Recent research has made significant progress in automatic patch generation, an approach to repair programs with less or no manual intervention. However, direct deployment of auto-generated patches remains difficult, for reasons such as patch quality ... expand

## A foundation for refactoring C with macros

Jeffrey L. Overbey, Farnaz Behrang, Munawar Hafiz
Pages: 75-85
doi>10.1145/2635868.2635908
Full text: PDFPDF

This paper establishes the concept of "preprocessor dependences" as a foundation for building automated refactoring tools that transform source code containing lexical macros and conditional compilation directives, such as those provided by the C preprocessor. ... expand

## Vector abstraction and concretization for scalable detection of refactorings

Narcisa Andreea Milea, Lingxiao Jiang, Siau-Cheng Khoo
Pages: 86-97
doi>10.1145/2635868.2635926
Full text: PDFPDF

Automated techniques have been proposed to either identify refactoring opportunities (i.e., code fragments that can be but have not yet been restructured in a program), or reconstruct historical refactorings (i.e., code restructuring operations that ... expand

# SESSION: Static Analysis

## FlowTwist: efficient context-sensitive inside-out taint analysis for large codebases

Johannes Lerch, Ben Hermann, Eric Bodden, Mira Mezini
Pages: 98-108
doi>10.1145/2635868.2635878
Full text: PDFPDF

Over the past years, widely used platforms such as the Java Class Library have been under constant attack through vulnerabilities that involve a combination of two taint-analysis problems: an integrity problem allowing attackers to trigger sensitive ... expand

## ORBS: language-independent program slicing

David Binkley, Nicolas Gold, Mark Harman, Syed Islam, Jens Krinke, Shin Yoo
Pages: 109-120
doi>10.1145/2635868.2635893
Full text: PDFPDF

Current slicing techniques cannot handle systems written in multiple programming languages. Observation-Based Slicing (ORBS) is a language-independent slicing technique capable of slicing multi-language systems, including systems which contain (third ... expand

##JSAI: a static analysis platform for JavaScript

Vineeth Kashyap, Kyle Dewey, Ethan A. Kuefner, John Wagner, Kevin Gibbons, John Sarracino, Ben Wiedermann, Ben Hardekopf
Pages: 121-132
doi>10.1145/2635868.2635904
Full text: PDFPDF

JavaScript is used everywhere from the browser to the server, including desktops and mobile devices. However, the current state of the art in JavaScript static analysis lags far behind that of other languages such as C and Java. Our goal is to help ... expand

## A path-sensitively sliced control flow graph

Joxan Jaffar, Vijayaraghavan Murali
Pages: 133-143
doi>10.1145/2635868.2635884
Full text: PDFPDF

We present a new graph representation of programs with specified target variables. These programs are intended to be processed by third-party applications querying target variables such as testers and verifiers. The representation embodies two concepts. ... expand

**Comment by GeorgePanzerMathew** [comment]
Done till page 189.
