### ISSUE TITLE
TCA: An Efficient Two-Mode Meta-Heuristic Algorithm for Combinatorial Test Generation (T)

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#773]
http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7372037&punumber%3D7371449%26filter%3DAND%28p_IS_Number%3A7371976%29%26pageNumber%3D3

**Comment by bigfatnoob** [comment]
No Data Found.
Tools available at : https://github.com/leiatpku/TCA
