### ISSUE TITLE
On the influence of maintenance activity types on the issue resolution time

### ISSUE THREAD

**Issue by boracaglayan** [opensciences/opensciences.github.io#81]
Paper Link
====
http://dl.acm.org/citation.cfm?id=2639506&CFID=609851366&CFTOKEN=28229506

Data Link
====
http://ghtorrent.org/relational.html

**Comment by Amoula1** [comment]
* Title: On the influence of maintenance activity types on the issue resolution time
* Authors: 
- Alessandro Murgia, alessandro.murgia@uantwerpen.be
- Giulio Concas, concas@diee.unica.it
- Roberto Tonelli, roberto.tonelli@diee.unica.it
- Marco Ortu, marco.ortu@diee.unica.it
- Serge Demeyer, serge.demeyer@uantwerpen.be
- Roberto Tonelli, roberto.tonelli@diee.unica.it
- Michele Marchesi, michele@diee.unica.it
* Main contribution: we investigate the influence of the maintenance type on issue resolution time.
* Findings: From GitHub’s issue repository, we analyze more than 14000 issue reports taken from 34 open source projects and classify them as corrective, adaptive, perfective or preventive maintenance. Based on this data, we show that the issue resolution time depends on the maintenance type.
* Data Link: https://github.com/gousiosg/github-mirror
* Data Description: To find the data there is a need to go to the paper "The GHTorent Dataset and Tool Suite" (The GHTorent project has been collecting data for all public projects available on Github for more than a year. In this paper, we present the dataset details and construction process and outline the challenges and research opportunities emerging from it ). 
-More than 900GB of raw data and 10GB of metadata have been collected.

**Comment by vivekaxl** [comment]
The link provided by Amoula1 points to GHTorrent, which is a mirror of Github (as mentioned). It doesn't have data. The authors didn't give a link to repo of issues then have analyzed.
