### ISSUE TITLE
Tracking and Analyzing Cross-Cutting Activities in Developers' Daily Work (N)

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#817]
http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7372016&punumber%3D7371449%26filter%3DAND%28p_IS_Number%3A7371976%29%26pageNumber%3D2

**Comment by bigfatnoob** [comment]
Data is too small: If interested here is the link. 
http://baolingfeng.weebly.com/uploads/5/0/3/8/50383961/accessiblity_survey.pdf
