### ISSUE TITLE
 Search-Based Synthesis of Probabilistic Models for Quality-of-Service Software Engineering (T)

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#822]
http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7372021&punumber%3D7371449%26filter%3DAND%28p_IS_Number%3A7371976%29%26pageNumber%3D2

**Comment by amritbhanu** [comment]
duplicate with #823
