### ISSUE TITLE
 LED: Tool for Synthesizing Web Element Locators

### ISSUE THREAD

**Issue by vivekaxl** [opensciences/opensciences.github.io#855]
http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7372078&punumber%3D7371449%26filter%3DAND%28p_IS_Number%3A7371976%29%26pageNumber%3D5

**Comment by azhe825** [comment]
LED
demo and download link: http://ece.ubc.ca/~kbajaj/led/
source code: https://github.com/saltlab/led

**Comment by dapryor** [comment]
added
