### ISSUE TITLE
FSE'14 Chunk #4

### ISSUE THREAD

**Issue by timm** [opensciences/opensciences.github.io#88]
# SESSION: Software Documentation

## Selection and presentation practices for code example summarization

Annie T. T. Ying, Martin P. Robillard
Pages: 460-471
doi>10.1145/2635868.2635877
Full text: PDFPDF

Code examples are an important source for answering questions about software libraries and applications. Many usage contexts for code examples require them to be distilled to their essence: e.g., when serving as cues to longer documents, or for reminding ... expand

## Mining idioms from source code

Miltiadis Allamanis, Charles Sutton
Pages: 472-483
doi>10.1145/2635868.2635901
Full text: PDFPDF

We present the first method for automatically mining code idioms from a corpus of previously written, idiomatic software projects. We take the view that a code idiom is a syntactic fragment that recurs across projects and has a single semantic purpose. ... expand

## Automatic generation of release notes

Laura Moreno, Gabriele Bavota, Massimiliano Di Penta, Rocco Oliveto, Andrian Marcus, Gerardo Canfora
Pages: 484-495
doi>10.1145/2635868.2635870
Full text: PDFPDF

This paper introduces ARENA (Automatic RElease Notes generAtor), an approach for the automatic generation of release notes. ARENA extracts changes from the source code, summarizes them, and integrates them with information from versioning systems and ... expand

# SESSION: Web Apps

## Discovering refactoring opportunities in cascading style sheets

Davood Mazinanian, Nikolaos Tsantalis, Ali Mesbah
Pages: 496-506
doi>10.1145/2635868.2635879
Full text: PDFPDF

Cascading Style Sheets (CSS) is a language used for describing the look and formatting of HTML documents. CSS has been widely adopted in web and mobile development practice, since it enables a clean separation of content from presentation. The language ... expand

## SAFEWAPI: web API misuse detector for web applications

SungGyeong Bae, Hyunghun Cho, Inho Lim, Sukyoung Ryu
Pages: 507-517
doi>10.1145/2635868.2635916
Full text: PDFPDF

The evolution of Web 2.0 technologies makes web applications prevalent in various platforms including mobile devices and smart TVs. While one of the driving technologies of web applications is JavaScript, the extremely dynamic features of JavaScript ... expand

## Building call graphs for embedded client-side code in dynamic web applications

Hung Viet Nguyen, Christian Kästner, Tien N. Nguyen
Pages: 518-529
doi>10.1145/2635868.2635928
Full text: PDFPDF

When developing and maintaining a software system, programmers often rely on IDEs to provide editor services such as syntax highlighting, auto-completion, and "jump to declaration". In dynamic web applications, such tool support is currently limited ... expand

# SESSION: Architecture and Design

## Sketches and diagrams in practice

Sebastian Baltes, Stephan Diehl
Pages: 530-541
doi>10.1145/2635868.2635891
Full text: PDFPDF

Sketches and diagrams play an important role in the daily work of software developers. In this paper, we investigate the use of sketches and diagrams in software engineering practice. To this end, we used both quantitative and qualitative methods. We ... expand

## Architecture challenges for internal software ecosystems: a large-scale industry case study

Klaus-Benedikt Schultis, Christoph Elsner, Daniel Lohmann
Pages: 542-552
doi>10.1145/2635868.2635876
Full text: PDFPDF

The idea of software ecosystems encourages organizations to open software projects for external businesses, governing the cross-organizational development by architectural and other measures. Even within a single organization, this paradigm can be of ... expand

## Variable-specific resolutions for feature interactions

Cecylia Bocovich, Joanne M. Atlee
Pages: 553-563
doi>10.1145/2635868.2635927
Full text: PDFPDF

Systems assembled from independently developed features suffer from feature interactions, in which features affect one another's behaviour in surprising ways. The feature-interaction problem states that the number of potential interactions is exponential ... expand

## An empirical study on program comprehension with reactive programming

Guido Salvaneschi, Sven Amann, Sebastian Proksch, Mira Mezini
Pages: 564-575
doi>10.1145/2635868.2635895
Full text: PDFPDF

Starting from the first investigations with strictly functional languages, reactive programming has been proposed as THE programming paradigm for reactive applications. The advantages of designs based on this style over designs based on the Observer ... expand

# SESSION: Mobile Apps

## Apposcopy: semantics-based detection of Android malware through static analysis
Yu Feng, Saswat Anand, Isil Dillig, Alex Aiken
Pages: 576-587
doi>10.1145/2635868.2635869
Full text: PDFPDF

We present Apposcopy, a new semantics-based approach for identifying a prevalent class of Android malware that steals private user information. Apposcopy incorporates (i) a high-level language for specifying signatures that describe semantic characteristics ... expand

## Detecting energy bugs and hotspots in mobile apps

Abhijeet Banerjee, Lee Kee Chong, Sudipta Chattopadhyay, Abhik Roychoudhury
Pages: 588-598
doi>10.1145/2635868.2635871
Full text: PDFPDF

Over the recent years, the popularity of smartphones has increased dramatically. This has lead to a widespread availability of smartphone applications. Since smartphones operate on a limited amount of battery power, it is important to develop tools ... expand

## EvoDroid: segmented evolutionary testing of Android apps

Riyadh Mahmood, Nariman Mirzaei, Sam Malek
Pages: 599-609
doi>10.1145/2635868.2635896
Full text: PDFPDF

Proliferation of Android devices and apps has created a demand for applicable automated software testing techniques. Prior research has primarily focused on either unit or GUI testing of Android apps, but not their end-to-end system testing in a systematic ... expand

## Prioritizing the devices to test your app on: a case study of Android game apps

Hammad Khalid, Meiyappan Nagappan, Emad Shihab, Ahmed E. Hassan
Pages: 610-620
doi>10.1145/2635868.2635909
Full text: PDFPDF

Star ratings that are given by the users of mobile apps directly impact the revenue of its developers. At the same time, for popular platforms like Android, these apps must run on hundreds of devices increasing the chance for device-specific problems. ... expand

# SESSION: Testing and Oracles

## Improving oracle quality by detecting brittle assertions and unused inputs in tests

Chen Huo, James Clause
Pages: 621-631
doi>10.1145/2635868.2635917
Full text: PDFPDF

Writing oracles is challenging. As a result, developers often create oracles that check too little, resulting in tests that are unable to detect failures, or check too much, resulting in tests that are brittle and difficult to maintain. In this paper ... expand

## On the efficiency of automated testing

Marcel Böhme, Soumya Paul
Pages: 632-642
doi>10.1145/2635868.2635923
Full text: PDFPDF

The aim of automated program testing is to gain confidence about a program's correctness by sampling its input space. The sampling process can be either systematic or random. For every systematic testing technique the sampling is informed by the ... expand

## An empirical analysis of flaky tests

Qingzhou Luo, Farah Hariri, Lamyaa Eloussi, Darko Marinov
Pages: 643-653
doi>10.1145/2635868.2635920
Full text: PDFPDF

Regression testing is a crucial part of software development. It checks that software changes do not break existing functionality. An important assumption of regression testing is that test outcomes are deterministic: an unmodified test is expected ... expand

## Are mutants a valid substitute for real faults in software testing?

René Just, Darioush Jalali, Laura Inozemtseva, Michael D. Ernst, Reid Holmes, Gordon Fraser
Pages: 654-665
doi>10.1145/2635868.2635929
Full text: PDFPDF

A good test suite is one that detects real faults. Because the set of faults in a program is usually unknowable, this definition is not useful to practitioners who are creating test suites, nor to researchers who are creating and evaluating tools that ... expand

**Comment by CarterPape** [comment]
Made "Maybe has data" issues for all papers
